### PR TITLE
RemoveThumbsCommand dialog error fix

### LINKED ISSUE #1258: RemoveThumbsCommand error: call of undefined helper 'dialog'
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.18.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/media-bundle              3.5.1  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0  Symfony SonataNotificationBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1 Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.8 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2 Symfony SwiftmailerBundle
symfony/symfony            v3.2.8 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.1.5-1+deb.sury.org~xenial+2 (cli) (built: May 22 2017 12:48:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5-1+deb.sury.org~xenial+2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

I'm trying to execute `sonata:media:remove-thumbnails` command, but the exception is thrown:

```bash
$ php bin/console sonata:media:remove-thumbnails -vvv

                                                                  
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The helper "dialog" is not defined.                             
                                                                  

Exception trace:
 () at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/HelperSet.php:82
 Symfony\Component\Console\Helper\HelperSet->get() at /path/to/my/project/vendor/sonata-project/media-bundle/Command/RemoveThumbsCommand.php:150
 Sonata\MediaBundle\Command\RemoveThumbsCommand->getProvider() at /path/to/my/project/vendor/sonata-project/media-bundle/Command/RemoveThumbsCommand.php:71
 Sonata\MediaBundle\Command\RemoveThumbsCommand->execute() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:853
 Symfony\Component\Console\Application->doRunCommand() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:200
 Symfony\Component\Console\Application->doRun() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /path/to/my/project/bin/console:28

sonata:media:remove-thumbnails [--batchSize BATCHSIZE] [--batchesLimit BATCHESLIMIT] [--startOffset STARTOFFSET] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<providerName>] [<context>] [<format>]
```

In the file `/path/to/my/project/vendor/sonata-project/media-bundle/Command/RemoveThumbsCommand.php:150` we can see next:

```php
/**
 * This command can be used to re-generate the thumbnails for all uploaded medias.
 *
 * Useful if you have existing media content and added new formats.z
 */
class RemoveThumbsCommand extends BaseCommand
{

    ...

    /**
     * @return MediaProviderInterface
     */
    public function getProvider()
    {
        $providerName = $this->input->getArgument('providerName');
        if (null === $providerName) {
            $providers = array_keys($this->getMediaPool()->getProviders());
            $dialog = $this->getHelperSet()->get('dialog'); // <------ problem on this line
            $providerKey = $dialog->select($this->output, 'Please select the provider', $providers);
            $providerName = $providers[$providerKey];
        }

        return $this->getMediaPool()->getProvider($providerName);
    }

    ...

}
```

## Steps to reproduce

Run `$ php bin/console sonata:media:remove-thumbnails`

## Expected results

Dialog with the questions about provider, etc.

## Actual results

Error: `Symfony\Component\Console\Exception\InvalidArgumentException The helper "dialog" is not defined.`

### PR DESCRIPTION
**Pull request by vyshkant**
I am targeting this branch, because my patch is fixing the bug existing in this branch.

Closes #1258 

## Changelog

```markdown
### Fixed
- Silent `sonata:media:remove-thumbnails` command when running this command without arguments.
```

## To do

- [x] Update the tests

## Subject

I'have fixed the call to undefined helper 'dialog'. Intead of 'dialog' the 'question' helper is used.

### CODE REVIEW

**Comment by vyshkant** [comment]
By all appearances, `RefreshMetadataCommand`, `SyncThumbsCommand` and `UpdateCdnStatusCommand` classes also have this bug. Tell me what should I fix in this PR and I'll fix the rest of these classes.

File: Command/RemoveThumbsCommand.php [hunk 1]
```diff
@@ -236,4 +263,26 @@ protected function log($message)
             $this->output->writeln($message);
         }
     }
+
+    /**
+     * @return QuestionHelper|DialogHelper
+     */
+    protected function getQuestionHelper()
```
Comment (core23) [inline Command/RemoveThumbsCommand.php]: Can you make this `private` or `final` please

Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: @core23 done

File: Command/RemoveThumbsCommand.php [hunk 2]
```diff
@@ -236,4 +263,27 @@ protected function log($message)
             $this->output->writeln($message);
         }
     }
+
+    /**
+     * @return QuestionHelper|DialogHelper
+     */
+    final protected function getQuestionHelper()
```
Comment (core23) [inline Command/RemoveThumbsCommand.php]: Why did you make this public? IMHO this is just a method for BC reasons. So please make this `private`

Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: I did not make this `public`. Did you mean `protected`? This should be changed to `private`, or `final protected` is OK?

Comment (core23) [inline Command/RemoveThumbsCommand.php]: Yes, this should either `private` or `final protected` if there is a reason. 

This method did only exist for BC reasons and will be removed when dropping old symfony version. Am I right? So please make this `private`

Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: Yes, you're right.

Done.

**Comment by vyshkant** [comment]
@OskarStark is current version OK?

**Comment by OskarStark** [comment]
> @OskarStark is current version OK?

Please explain what you fixed exactly and why

**Comment by vyshkant** [comment]
Now is OK?

**Comment by vyshkant** [comment]
@OskarStark, @core23 what do yout think?

**Comment by vyshkant** [comment]
@Soullivaneuh Done.
It's okay now?

File: Command/RemoveThumbsCommand.php [hunk 3]
```diff
@@ -146,10 +149,18 @@ public function getProvider()
     {
         $providerName = $this->input->getArgument('providerName');
         if (null === $providerName) {
+            $questionHelper = $this->getQuestionHelper();
```
Comment (Soullivaneuh) [inline Command/RemoveThumbsCommand.php]: I'm quite :-1: about storing the question helper on a variable multiple time during the command.

Calling it directly from `$this` would be enough and clearer IMHO.

Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: @Soullivaneuh I've made the required changes

**Comment by Soullivaneuh** [comment]
Also coverage decreased, could you please take a look?Also coverage decreased, could you please take a look?

File: Command/RemoveThumbsCommand.php [hunk 4]
```diff
@@ -236,4 +257,27 @@ protected function log($message)
...
+
+    /**
+     * @return QuestionHelper|DialogHelper
+     */
+    private function getQuestionHelper()
+    {
+        // NEXT_MAJOR: Remove this BC code for SensioGeneratorBundle 2.3/2.4 after dropping support for Symfony 2.3
+        if (class_exists('Sensio\Bundle\GeneratorBundle\Command\Helper\DialogHelper')) {
+            $questionHelper = $this->getHelper('dialog');
+            if (!$questionHelper instanceof DialogHelper) {
```
Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: I don't understand, what exactly can be simplified here and below. Can you please explain, what do you mean?

**Comment by vyshkant** [comment]
> Also coverage decreased, could you please take a look?Also coverage decreased, could you please take a look?

Sorry, but I do not know what does the coverage percentage mean. Maybe its decreasing is caused by creating one more method (`private function getQuestionHelper`)? What should I do to fix this ploblem?

File: Command/RemoveThumbsCommand.php (hunk 4 above)
Comment (Soullivaneuh) [inline Command/RemoveThumbsCommand.php]: This can be merge to this `if` statement: https://github.com/sonata-project/SonataMediaBundle/pull/1259/files#diff-b434675e69b14ff482819901a0366360R267

**Comment by greg0ire** [comment]
@vykshant cover the method with tests?

File: Command/RemoveThumbsCommand.php (hunk 4 above)
Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: @Soullivaneuh Do you mean something like this:
```php
    /**
     * @return QuestionHelper|DialogHelper
     */
    private function getQuestionHelper()
    {
        // NEXT_MAJOR: Remove this BC code for SensioGeneratorBundle 2.3/2.4 after dropping support for Symfony 2.3
        if (class_exists('Sensio\Bundle\GeneratorBundle\Command\Helper\DialogHelper') && !($questionHelper = $this->getHelper('dialog')) instanceof DialogHelper) {
            $questionHelper = new DialogHelper();
            $this->getHelperSet()->set($questionHelper);
        } elseif (!($questionHelper = $this->getHelper('question')) instanceof QuestionHelper) {
            $questionHelper = new QuestionHelper();
            $this->getHelperSet()->set($questionHelper);
        }

        return $questionHelper;
    }
```

**Comment by vyshkant** [comment]
> @vyshkant cover the method with tests?

What kind of test should be written? I did not find the `RemoveThumbsCommand` test case, so should I write tests for the whole `RemoveThumbsCommand`?

**Comment by OskarStark** [comment]
> so should I write tests for the whole RemoveThumbsCommand?

this would be awesome, you could use other command tests as an example, not sure if we have some in the media bundle, but in the page-bundle

**Comment by greg0ire** [comment]
> so should I write tests for the whole RemoveThumbsCommand

Please give it your best try, and if it's too hard, tell us.

**Comment by greg0ire** [comment]
> so should I write tests for the whole RemoveThumbsCommand

Please give it your best try, and if it's too hard, just let us know.

File: Command/RemoveThumbsCommand.php (hunk 4 above)
Comment (Soullivaneuh) [inline Command/RemoveThumbsCommand.php]: Yes. BTW, I think the usage of instanceof is enough for this case. @greg0ire what do you think?

Comment (greg0ire) [inline Command/RemoveThumbsCommand.php]: I think you're right: https://3v4l.org/kPrMT :+1:

**Comment by vyshkant** [comment]
@OskarStark, @greg0ire I wrote a small test-stub for this command. Before I push, could you please tell me how can I run tests on my local machine in the proper way?

**Comment by OskarStark** [comment]
`vendor/bin/phpunit` should do the trick

**Comment by greg0ire** [comment]
@OskarStark `phpunit` does not come along with Sonata. You have to install the phar yourself.

**Comment by OskarStark** [comment]
> @OskarStark phpunit does not come along with Sonata. You have to install the phar yourself.

ah damn you are right 👍

**Comment by vyshkant** [comment]
OK.

And one more question: after I ran `composer install`, the `sensio/generator-bundle` was not installed.

So neither `Sensio\Bundle\GeneratorBundle\Command\Helper\DialogHelper` nor `Sensio\Bundle\GeneratorBundle\Command\Helper\QuestionHelper` is available.

Is this OK? Why `SonataMediaBundle` doesn't have the `require-dev` dependency of `sensio/generator-bundle`?

**Comment by greg0ire** [comment]
> Why SonataMediaBundle doesn't have the require-dev dependency of sensio/generator-bundle?

Because that's how little this is tested. Please add it ;)

**Comment by vyshkant** [comment]
Ok. And I think, it is `require`, not `require-dev` dependency, because this functionality is needed not for **this package** developing reasons.

File: Command/RemoveThumbsCommand.php (hunk 4 above)
Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: @Soullivaneuh I think the usage of instanceof is **not** enough, because we're not only checking the variable by `instaceof`, but we're also creating `new DialogHelper()`.

So simplified code like this will probably cause a bug:
```php
    /**
     * @return QuestionHelper|DialogHelper
     */
    private function getQuestionHelper()
    {
        // NEXT_MAJOR: Remove this BC code for SensioGeneratorBundle 2.3/2.4 after dropping support for Symfony 2.3
        if (!($questionHelper = $this->getHelper('dialog')) instanceof DialogHelper) {
            $questionHelper = new DialogHelper();
            $this->getHelperSet()->set($questionHelper);
        } elseif (!($questionHelper = $this->getHelper('question')) instanceof QuestionHelper) {
            $questionHelper = new QuestionHelper();
            $this->getHelperSet()->set($questionHelper);
        }

        return $questionHelper;
    }
```
because `!($questionHelper = $this->getHelper('dialog')) instanceof DialogHelper` will return `true` even if the class `Sensio\Bundle\GeneratorBundle\Command\Helper\DialogHelper` does not exist — and in the next line we're trying to create new instance of not existing class.

**Comment by vyshkant** [comment]
> @OskarStark phpunit does not come along with Sonata. You have to install the phar yourself.

I've tried to run `php vendor/bin/simple-phpunit` but got many of the same errors (not only in my test): `Error: Class 'Prophecy\Prophet' not found`.

Does anybody know, what is wrong? Running the `simple-phpunit` is bad idea?

**Comment by greg0ire** [comment]
You can use simple phpunit if you want, but I think you have to specify you need prophecy in some way (an env variable IIRC)

**Comment by vyshkant** [comment]
And I also got some warnings while running tests:
```
There was 1 warning:

1) MediaExtensionTest::testThumbnailHasAllNecessaryAttributes
Cannot stub or mock class or interface "Twig_TemplateInterface" which does not exist

/path/to/SonataMediaBundle/vendor/symfony/phpunit-bridge/bin/.phpunit/phpunit-5.7/phpunit:5

WARNINGS!
Tests: 237, Assertions: 618, Warnings: 1.

Remaining deprecation notices (22)

Symfony\Component\HttpKernel\DependencyInjection\Extension::addClassesToCompile() is deprecated since version 3.3, to be removed in 4.0: 17x
    12x in SonataMediaExtensionTest::setUp from Sonata\MediaBundle\Tests\DependencyInjection
    1x in SonataMediaExtensionTest::testLoadWithDefaultAndCustomCategoryManager from Sonata\MediaBundle\Tests\DependencyInjection
    1x in SonataMediaExtensionTest::testLoadWithForceDisableTrueAndWithCategoryManager from Sonata\MediaBundle\Tests\DependencyInjection
    1x in SonataMediaExtensionTest::testLoadWithDefaultAndClassificationBundleEnable from Sonata\MediaBundle\Tests\DependencyInjection
    1x in SonataMediaExtensionTest::testLoadWithDefaultAndClassificationBundleEnableAndForceDisableCategory from Sonata\MediaBundle\Tests\DependencyInjection
    1x in SonataMediaExtensionTest::testLoadWithDefaultAndClassificationBundleEnableAndCustomCategoryManager from Sonata\MediaBundle\Tests\DependencyInjection

FOS\RestBundle\Context\Context::setMaxDepth is deprecated since version 2.1 and will be removed in 3.0. Use FOS\RestBundle\Context\Context::enableMaxDepth() and FOS\RestBundle\Context\Context::disableMaxDepth() instead: 4x
    1x in GalleryControllerTest::testPostGalleryMediaGalleryhasmediaAction from Sonata\MediaBundle\Tests\Controller\Api
    1x in GalleryControllerTest::testPutGalleryMediaGalleryhasmediaAction from Sonata\MediaBundle\Tests\Controller\Api
    1x in MediaControllerTest::testPutMediumAction from Sonata\MediaBundle\Tests\Controller\Api
    1x in MediaControllerTest::testPostProviderMediumAction from Sonata\MediaBundle\Tests\Controller\Api

Initializing Sonata\BlockBundle\Block\Service\MenuBlockService with an array parameter is deprecated since 3.x and will be removed in 4.0: 1x
    1x in BreadcrumbTest::testBlockService from Sonata\MediaBundle\Tests\Block\Breadcrumb

Legacy deprecation notices (3)
```

Should I create some issues?

**Comment by greg0ire** [comment]
> Should I create some issues?

Yes please. And, if you have the time, resolve them :P

**Comment by vyshkant** [comment]
Sorry for so many questions, but I'll ask one more.

I've created and pushed the `RemoveThumbsCommandTest`. Now this is dummy test (all it's lines are commented out), because the `RemoveThumbsCommand` interacts with the user, so if I just run it's test, this will stop the test running forever (because the `RemoveThumbsCommand` is waiting for user input).

Could you please advise me what and how should be run so that this problem does not arise?

**Comment by vyshkant** [comment]
> Yes please. And, if you have the time, resolve them :P
See #1267

**Comment by greg0ire** [comment]
@vyshkant this might help: https://symfony.com/doc/3.0/components/console/helpers/questionhelper.html#testing-a-command-that-expects-input

File: Command/RemoveThumbsCommand.php (hunk 4 above)
Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: @Soullivaneuh @greg0ire Or maybe it is better to remove `new DialogHelper` and `new QuestionHelper` sections? Are they really neccesary? I took this code fragment from here https://github.com/sonata-project/SonataAdminBundle/pull/4339

**Comment by vyshkant** [comment]
@greg0ire, @Soullivaneuh, @OskarStark, @core23  could you please review my PR again, because I'have changed some stuff in `RemoveThumbsCommand`.
And I'm also not sure if my test is OK, so I'm ready to listen to the comments.

File: Command/RemoveThumbsCommand.php [hunk 5]
```diff
@@ -61,27 +64,22 @@ public function configure()
     /**
      * {@inheritdoc}
      */
-    public function execute(InputInterface $input, OutputInterface $output)
+    protected function execute(InputInterface $input, OutputInterface $output)
```
Comment (jordisala1991) [inline Command/RemoveThumbsCommand.php]: why this change from public to protected?

File: Command/RemoveThumbsCommand.php [hunk 6]
```diff
@@ -140,53 +135,73 @@ public function execute(InputInterface $input, OutputInterface $output)
     }
 
     /**
+     * @param string $providerName
+     *
      * @return MediaProviderInterface
      */
-    public function getProvider()
+    protected function getProvider($providerName)
```
Comment (jordisala1991) [inline Command/RemoveThumbsCommand.php]: same here

File: Command/RemoveThumbsCommand.php (hunk 5 above)
Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: Because the parent class method is `protected`. So I don't see any reasons to keep this `public`.

File: Command/RemoveThumbsCommand.php (hunk 6 above)
Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: Because this method is only used inside this command.

File: Command/RemoveThumbsCommand.php (hunk 5 above)
Comment (jordisala1991) [inline Command/RemoveThumbsCommand.php]: not sure if we should consider this BC or not. @greg0ire what do you say?

Comment (greg0ire) [inline Command/RemoveThumbsCommand.php]: I can live with it.

File: Command/RemoveThumbsCommand.php (hunk 6 above)
Comment (Soullivaneuh) [inline Command/RemoveThumbsCommand.php]: Maybe, but this is not a parent class constraint and this is BC break.

Comment (vyshkant) [inline Command/RemoveThumbsCommand.php]: > Maybe, but this is not a parent class constraint and this is BC break.

@Soullivaneuh Do you mean I only have to change `getContext`, `getProvider` and `getFormat` methods back to public with the same arguments, or change the `execute` method too?

**Comment by vyshkant** [comment]
What should I do to make this PR finally merged?

**Comment by jordisala1991** [comment]
Can you take a look at the last @Soullivaneuh review?

File: composer.json [hunk 7]
```diff
@@ -23,6 +23,7 @@
         "knplabs/gaufrette": "^0.1.6 || ^0.2 || ^0.3",
         "kriswallsmith/buzz": "^0.15",
         "psr/log": "^1.0",
+        "sensio/generator-bundle": "^2.3 || ^3.0",
```
Comment (jordisala1991) [inline composer.json]: Can you make that ^3.1

(We are droping support for SF 2.3 to 2.7) Look: https://github.com/sonata-project/SonataMediaBundle/pull/1307

File: Command/RemoveThumbsCommand.php [hunk 8]
```diff
@@ -161,11 +164,18 @@ public function getProvider()
...
     {
         $context = $this->input->getArgument('context');
+
         if (null === $context) {
             $contexts = array_keys($this->getMediaPool()->getContexts());
-            $dialog = $this->getHelperSet()->get('dialog');
-            $contextKey = $dialog->select($this->output, 'Please select the context', $contexts);
-            $context = $contexts[$contextKey];
+
+            // NEXT_MAJOR: Remove this BC code for SensioGeneratorBundle 2.3/2.4 after dropping support for Symfony 2.3
```
Comment (jordisala1991) [inline Command/RemoveThumbsCommand.php]: This BC layer will not be needed, we are droping support for SF 2.3

**Comment by vyshkant** [comment]
Now this PR can be merged?

**Comment by greg0ire** [comment]
Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

How to do that?

1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already pushed. Don't forget the `--force` option otherwise git will try to merge both things together.

File: .github/ISSUE_TEMPLATE.md [hunk 9]
```diff
@@ -12,21 +12,19 @@
 
 #### Sonata packages
 
-```bash
-$ composer show sonata-project/*
-# Put the result here.
+```
+$ composer show --latest 'sonata-project/*'
```
Comment (greg0ire) [inline .github/ISSUE_TEMPLATE.md]: This is not normal.

Comment (vyshkant) [reply .github/ISSUE_TEMPLATE.md]: This is not a part of my changes. Maybe this is a result of `rebase`? I did something wrong?

**Comment by greg0ire** [comment]
How to rebase properly:

1. Fetch all new commits: `git fetch --all`. ⬇️ 
2. Rebase on what you fetched interactively: ✂️ 
    1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin repository.
    2. A window will show up with many lines, remove every line but the last one, which should correspond to your commit.
   2. If you run into a conflict: 💥 
        1. fix it with `git mergetool`. 😷 
        1. continue on your merry way with `git rebase --continue`. ⏩ 
3. Force push to overwrite all this : `git push --force`. ⬆️

**Comment by vyshkant** [comment]
> Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

It looks like I coped with this.

But `$ composer show --latest 'sonata-project/*'` is still in `.github/ISSUE_TEMPLATE.md`. As I can see, this is an actual content of https://github.com/sonata-project/SonataMediaBundle/blob/3.x/.github/ISSUE_TEMPLATE.md, so even if it's not normal, it's not my fault.

**Comment by greg0ire** [comment]
> But $ composer show --latest 'sonata-project/*' is still in .github/ISSUE_TEMPLATE.md. As I can see, this is an actual content of https://github.com/sonata-project/SonataMediaBundle/blob/3.x/.github/ISSUE_TEMPLATE.md, so even if it's not normal, it's not my fault.

I don't see that in the diff...

File: Command/CleanMediaCommand.php [hunk 10]
```diff
@@ -13,7 +13,6 @@
 
 use Sonata\MediaBundle\Provider\FileProvider;
 use Sonata\MediaBundle\Provider\MediaProviderInterface;
-use Sonata\MediaBundle\Provider\Pool;
```
Comment (greg0ire) [inline Command/CleanMediaCommand.php]: ?

File: Command/RemoveThumbsCommand.php [hunk 11]
```diff
@@ -238,4 +234,14 @@ protected function log($message)
             $this->output->writeln($message);
         }
     }
+
+    /**
+     * Get question helper or the dialog helper for SensioGeneratorBundle 2.3/2.4 compatibility.
+     *
+     * @return QuestionHelper
+     */
+    private function getQuestionHelper()
```
Comment (greg0ire) [inline Command/RemoveThumbsCommand.php]: Please add return type hinting and remove the `@return` comment

File: Command/RemoveThumbsCommand.php [hunk 12]
```diff
@@ -238,4 +234,14 @@ protected function log($message)
             $this->output->writeln($message);
         }
     }
+
+    /**
+     * Get question helper or the dialog helper for SensioGeneratorBundle 2.3/2.4 compatibility.
```
Comment (greg0ire) [inline Command/RemoveThumbsCommand.php]: Please check if this is still necessary

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 13]
```diff
@@ -0,0 +1,155 @@
...
+
+    /**
+     * @var \PHPUnit_Framework_MockObject_MockObject|Pool
+     */
+    private $pool;
+
+    /**
+     * @var \PHPUnit_Framework_MockObject_MockObject|MediaManagerInterface
+     */
+    private $mediaManager;
```
Comment (greg0ire) [inline Tests/Command/RemoveThumbsCommandTest.php]: Why are some protected?

**Comment by vyshkant** [comment]
> I don't see that in the diff..

I think this is OK, 'cause I did not change this file. I think it has disappeared from the diff after I made `rebase` in the correct way.

File: Command/CleanMediaCommand.php (hunk 10 above)
Comment (vyshkant) [reply Command/CleanMediaCommand.php]: This import is never used in the file.

Comment (greg0ire) [reply Command/CleanMediaCommand.php]: Unrelated to your PR, but ok, sure!

File: Tests/Command/RemoveThumbsCommandTest.php (hunk 13 above)
Comment (vyshkant) [reply Tests/Command/RemoveThumbsCommandTest.php]: I made this test case on the `CleanMediaCommandTest` sample. In `CleanMediaCommandTest` class  some properties are `protected`. I don't need this. Should I change they to `private`?

File: Command/RemoveThumbsCommand.php (hunk 11 above)
Comment (vyshkant) [reply Command/RemoveThumbsCommand.php]: Do you mean php7-style (`private function getQuestionHelper(): QuestionHelper`)?
Should I do the same with other functions?

Comment (greg0ire) [reply Command/RemoveThumbsCommand.php]: Yes, absolutely please.

File: Tests/Command/RemoveThumbsCommandTest.php (hunk 13 above)
Comment (greg0ire) [reply Tests/Command/RemoveThumbsCommandTest.php]: Make everything private by default. http://fabien.potencier.org/pragmatism-over-theory-protected-vs-private.html

File: Tests/Command/TestCase.php [hunk 14]
```diff
@@ -0,0 +1,30 @@
...
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Sonata\MediaBundle\Tests\Command;
+
+use Symfony\Component\Filesystem\Tests\FilesystemTestCase;
+
+if (class_exists('Symfony\Component\Filesystem\Tests\FilesystemTestCase')) {
```
Comment (jordisala1991) [inline Tests/Command/TestCase.php]: You don't have to do this trick anymore, form SF >=2.8 there is always this class.

File: Tests/Command/CleanMediaCommandTest.php [hunk 15]
```diff
@@ -20,17 +20,6 @@
 use Symfony\Component\Console\Output\OutputInterface;
 use Symfony\Component\Console\Tester\CommandTester;
 use Symfony\Component\DependencyInjection\ContainerInterface;
-use Symfony\Component\Filesystem\Tests\FilesystemTestCase;
```
Comment (jordisala1991) [inline Tests/Command/CleanMediaCommandTest.php]: You can keep this line and make this testClass extend directly from it. Also you can remove this line:

`@requires function Symfony\Component\Filesystem\Tests\FilesystemTestCase::setUpBeforeClass`

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 16]
```diff
@@ -0,0 +1,150 @@
...
+use Sonata\MediaBundle\Tests\Entity\Media;
+use Symfony\Component\Console\Application;
+use Symfony\Component\Console\Tester\CommandTester;
+use Symfony\Component\DependencyInjection\ContainerInterface;
+
+/**
+ * @author Anton Dyshkant <vyshkant@gmail.com>
+ *
+ * @requires function Symfony\Component\Filesystem\Tests\FilesystemTestCase::setUpBeforeClass
+ * @requires function Symfony\Component\Console\Input::setStream
```
Comment (jordisala1991) [inline Tests/Command/RemoveThumbsCommandTest.php]: Why this require?

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 17]
```diff
@@ -0,0 +1,150 @@
...
+ */
+class RemoveThumbsCommandTest extends TestCase
```
Comment (jordisala1991) [inline Tests/Command/RemoveThumbsCommandTest.php]: Extend directly from FileSystemTestCase and remove `@requires function Symfony\Component\Filesystem\Tests\FilesystemTestCase::setUpBeforeClass` section above

File: Tests/Command/TestCase.php [hunk 18]
```diff
@@ -0,0 +1,21 @@
...
+ */
+
+namespace Sonata\MediaBundle\Tests\Command;
+
+use Symfony\Component\Filesystem\Tests\FilesystemTestCase;
+
+/**
+ * @author Sullivan Senechal <soullivaneuh@gmail.com>
+ */
+class TestCase extends FilesystemTestCase
```
Comment (jordisala1991) [inline Tests/Command/TestCase.php]: You can remove this file

**Comment by jordisala1991** [comment]
Note: --prefer-lowest will fail because the other PR is still not merged, so we are using SF 2.3.

Once the other PR gets merged, we will be using atleast 2.8

**Comment by vyshkant** [comment]
I think I've implemented all requested changes.

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 19]
```diff
@@ -0,0 +1,148 @@
...
+
+        $this->mediaManager->expects($this->exactly(2))->method('findBy')->will($this->returnCallback(function (array $criteria, array $orderBy = null, $limit = null, $offset = null) use ($medias) {
+            if (null !== $offset && $offset > 0) {
+                return [];
+            }
+
+            return $medias;
+        }));
+
+        $this->tester->setInputs(['fooprovider', 'foo', 'small']);
```
Comment (jordisala1991) [inline Tests/Command/RemoveThumbsCommandTest.php]: This line is making travis fail, can you take a look at it?

Comment (vyshkant) [reply Tests/Command/RemoveThumbsCommandTest.php]: I think there is another problem:
> TypeError: Return value of Sonata\MediaBundle\Command\RemoveThumbsCommand::getQuestionHelper() must be an instance of Sensio\Bundle\GeneratorBundle\Command\Helper\QuestionHelper, instance of Symfony\Component\Console\Helper\QuestionHelper returned

So all this time we were accessing a different helper, when we were calling `$this->getHelper('question')`.

File: Command/RemoveThumbsCommand.php [hunk 20]
```diff
@@ -141,33 +134,29 @@ public function execute(InputInterface $input, OutputInterface $output)
         $this->log("Done (total medias processed: {$totalMediasCount}).");
     }
 
-    /**
-     * @return MediaProviderInterface
-     */
-    public function getProvider()
+    public function getProvider(): MediaProviderInterface
```
Comment (core23) [inline Command/RemoveThumbsCommand.php]: Adding return types (on a non-final class) is a BC break!

https://3v4l.org/aN79d

Comment (jordisala1991) [reply Command/RemoveThumbsCommand.php]: recover the old signature please for all the methods except the one you created

Comment (greg0ire) [reply Command/RemoveThumbsCommand.php]: Oh sorry @vyshkant that's my fault

**Comment by vyshkant** [comment]
@Soullivaneuh @greg0ire @core23 @jordisala1991 @OskarStark now this PR can be merged?

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 21]
```diff
@@ -0,0 +1,150 @@
...
+use Symfony\Component\Console\Tester\CommandTester;
+use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\Filesystem\Tests\FilesystemTestCase;
+
+/**
+ * @author Anton Dyshkant <vyshkant@gmail.com>
+ *
+ * @requires function Symfony\Component\Console\Tester\CommandTester::setInputs
+ */
+class RemoveThumbsCommandTest extends FilesystemTestCase
```
Comment (Soullivaneuh) [inline Tests/Command/RemoveThumbsCommandTest.php]: `final`

Comment (vyshkant) [reply Tests/Command/RemoveThumbsCommandTest.php]: @Soullivaneuh done

**Comment by jordisala1991** [comment]
Please review @sonata-project/contributors @Soullivaneuh

File: Command/RemoveThumbsCommand.php [hunk 22]
```diff
@@ -238,4 +234,9 @@ protected function log($message)
             $this->output->writeln($message);
         }
     }
+
+    private function getQuestionHelper(): QuestionHelper
```
Comment (ZRazor) [inline Command/RemoveThumbsCommand.php]: This won't work with PHP < 7.0

Comment (ZRazor) [reply Command/RemoveThumbsCommand.php]: I see that php < 7.1 is dropped in 3.x, but if I have php 7.0 and sf3, how can I receive this patch?

Comment (greg0ire) [reply Command/RemoveThumbsCommand.php]: @ZRazor by upgrading, or by ignoring platform requirements with composer (not recommended)

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 23]
```diff
@@ -0,0 +1,150 @@
...
+
+        $this->tester = new CommandTester($this->application->find('sonata:media:remove-thumbnails'));
+
+        $this->pool = $pool = $this->getMockBuilder('Sonata\MediaBundle\Provider\Pool')->disableOriginalConstructor()->getMock();
+
+        $this->mediaManager = $mediaManager = $this->getMockBuilder('Sonata\MediaBundle\Model\MediaManagerInterface')->getMock();
+
+        $this->container->expects($this->any())
+            ->method('get')
+            ->will($this->returnCallback(function ($id) use ($pool, $mediaManager) {
```
Comment (jlamur) [inline Tests/Command/RemoveThumbsCommandTest.php]: No need to add a `use` in this callback. You can call directly `$this->pool` and `$this->mediaManager` inside the callback.

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 24]
```diff
@@ -0,0 +1,150 @@
...
+        $this->command->setContainer($this->container);
+
+        $this->application = new Application();
+        $this->application->add($this->command);
+
+        $this->tester = new CommandTester($this->application->find('sonata:media:remove-thumbnails'));
+
+        $this->pool = $pool = $this->getMockBuilder('Sonata\MediaBundle\Provider\Pool')->disableOriginalConstructor()->getMock();
+
+        $this->mediaManager = $mediaManager = $this->getMockBuilder('Sonata\MediaBundle\Model\MediaManagerInterface')->getMock();
```
Comment (jlamur) [inline Tests/Command/RemoveThumbsCommandTest.php]: Please line-break every line that has more than 80 chars https://dev.to/greg0ire/why-i-keep-pestering-everyone-about-long-lines/

Comment (Soullivaneuh) [reply Tests/Command/RemoveThumbsCommandTest.php]: BTW, using `MediaManagerInterface::class` would help a lot.

Comment (Soullivaneuh) [reply Tests/Command/RemoveThumbsCommandTest.php]: And no @jlamur, the max is not 80 but 120.

http://www.php-fig.org/psr/psr-2/

Comment (greg0ire) [reply Tests/Command/RemoveThumbsCommandTest.php]: The rule I personally apply is: line-break every line that has more than 120 chars to a few lines that have less than 80 chars.

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 25]
```diff
@@ -0,0 +1,150 @@
...
+     */
+    private $tester;
+
+    /**
+     * @var \PHPUnit_Framework_MockObject_MockObject|Pool
+     */
+    private $pool;
+
+    /**
+     * @var \PHPUnit_Framework_MockObject_MockObject|MediaManagerInterface
```
Comment (Soullivaneuh) [inline Tests/Command/RemoveThumbsCommandTest.php]: Should be reversed. MediaManagerInterface is more important to clarify the type than the mock.

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 26]
```diff
@@ -0,0 +1,150 @@
...
+
+        $this->command = new RemoveThumbsCommand();
+        $this->command->setContainer($this->container);
+
+        $this->application = new Application();
+        $this->application->add($this->command);
+
+        $this->tester = new CommandTester($this->application->find('sonata:media:remove-thumbnails'));
+
+        $this->pool = $pool = $this->getMockBuilder('Sonata\MediaBundle\Provider\Pool')->disableOriginalConstructor()->getMock();
```
Comment (Soullivaneuh) [inline Tests/Command/RemoveThumbsCommandTest.php]: What it the point creating a `$pool` var?

Use only `$this->pool` instead.

File: Tests/Command/RemoveThumbsCommandTest.php (hunk 24 above)
Comment (Soullivaneuh) [inline Tests/Command/RemoveThumbsCommandTest.php]: Use `$this->mediaManager` directly.

File: Tests/Command/RemoveThumbsCommandTest.php (hunk 25 above)
Comment (greg0ire) [reply Tests/Command/RemoveThumbsCommandTest.php]: Plus, the mock uses inheritance, right?

**Comment by vyshkant** [comment]
@Soullivaneuh Can it be merged now?

File: Command/RemoveThumbsCommand.php [hunk 27]
```diff
@@ -147,11 +140,12 @@ public function execute(InputInterface $input, OutputInterface $output)
...
     {
         $providerName = $this->input->getArgument('providerName');
+
         if (null === $providerName) {
             $providers = array_keys($this->getMediaPool()->getProviders());
-            $dialog = $this->getHelperSet()->get('dialog');
-            $providerKey = $dialog->select($this->output, 'Please select the provider', $providers);
-            $providerName = $providers[$providerKey];
+
+            $question = new ChoiceQuestion('Please select the provider', $providers);
```
Comment (Soullivaneuh) [inline Command/RemoveThumbsCommand.php]: This variable seems to be use only one time.

It should not be initialized.

cc @greg0ire

File: Command/RemoveThumbsCommand.php [hunk 28]
```diff
@@ -163,11 +157,12 @@ public function getProvider()
...
     {
         $context = $this->input->getArgument('context');
+
         if (null === $context) {
             $contexts = array_keys($this->getMediaPool()->getContexts());
-            $dialog = $this->getHelperSet()->get('dialog');
-            $contextKey = $dialog->select($this->output, 'Please select the context', $contexts);
-            $context = $contexts[$contextKey];
+
+            $question = new ChoiceQuestion('Please select the context', $contexts);
```
Comment (Soullivaneuh) [inline Command/RemoveThumbsCommand.php]: This variable seems to be use only one time.

It should not be initialized.

cc @greg0ire

File: Command/RemoveThumbsCommand.php [hunk 29]
```diff
@@ -182,13 +177,14 @@ public function getContext()
...
         $format = $this->input->getArgument('format');
+
         if (null === $format) {
             $formats = array_keys($provider->getFormats());
             $formats[] = '<ALL THUMBNAILS>';
 
-            $dialog = $this->getHelperSet()->get('dialog');
-            $formatKey = $dialog->select($this->output, 'Please select the format', $formats);
-            $format = $formats[$formatKey];
+            $question = new ChoiceQuestion('Please select the format', $formats);
```
Comment (Soullivaneuh) [inline Command/RemoveThumbsCommand.php]: This variable seems to be use only one time.

It should not be initialized.

cc @greg0ire

Comment (greg0ire) [reply Command/RemoveThumbsCommand.php]: Dude...

Comment (greg0ire) [reply Command/RemoveThumbsCommand.php]: stahp

Comment (Soullivaneuh) [reply Command/RemoveThumbsCommand.php]: @greg0ire Sorry for the copy paste.

Plus, I never remember the rules name, I have to write it somewhere. :trollface:

Comment (greg0ire) [reply Command/RemoveThumbsCommand.php]: Just bookmark this: https://a-nickels-worth.blogspot.fr/2016/04/a-guide-to-naming-variables.html ;)

**Comment by vyshkant** [comment]
Now we are waiting for https://github.com/sonata-project/SonataMediaBundle/pull/1315

**Comment by OskarStark** [comment]
@vyshkant #1315 is merged!

**Comment by vyshkant** [comment]
@Soullivaneuh everything is OK?

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 30]
```diff
@@ -0,0 +1,184 @@
...
+    private $mediaManager;
+
+    /**
+     * {@inheritdoc}
+     */
+    protected function setUp()
+    {
+        parent::setUp();
+
+        $this->container = $this->getMockBuilder(ContainerInterface::class)
```
Comment (OskarStark) [inline Tests/Command/RemoveThumbsCommandTest.php]: can you use `createMock()` here?

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 31]
```diff
@@ -0,0 +1,184 @@
...
+        $this->application = new Application();
+        $this->application->add($this->command);
+
+        $this->tester = new CommandTester($this->application->find('sonata:media:remove-thumbnails'));
+
+        $this->pool = $this->getMockBuilder(Pool::class)
+            ->disableOriginalConstructor()
+            ->getMock();
+
+        $this->mediaManager = $this->getMockBuilder(MediaManagerInterface::class)
```
Comment (OskarStark) [inline Tests/Command/RemoveThumbsCommandTest.php]: `createMock`

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 32]
```diff
@@ -0,0 +1,184 @@
...
+            'providers' => [],
+            'formats' => [],
+            'download' => [],
+        ];
+
+        $formats = [
+            'small' => [],
+        ];
+
+        $filesystem = $this->getMockBuilder(Filesystem::class)
```
Comment (OskarStark) [inline Tests/Command/RemoveThumbsCommandTest.php]: `createMock`

File: Tests/Command/RemoveThumbsCommandTest.php [hunk 33]
```diff
@@ -0,0 +1,184 @@
...
+            ->disableOriginalConstructor()
+            ->getMock();
+
+        $fileProvider = $this->getMockBuilder(FileProvider::class)
```
Comment (OskarStark) [inline Tests/Command/RemoveThumbsCommandTest.php]: please check the other `->getMockBuilder(..foo..)->getMock();`, too and try `createMock()` instead

**Comment by vyshkant** [comment]
@OskarStark done!

File: Command/RemoveThumbsCommand.php (hunk 22 above)
Comment (greg0ire) [reply Command/RemoveThumbsCommand.php]: @ZRazor we ended up restoring compatibility.
@vyshkant that means you need to change that.

Comment (greg0ire) [reply Command/RemoveThumbsCommand.php]: Well it's actually not done yet, see https://github.com/sonata-project/SonataMediaBundle/pull/1314

**Comment by vyshkant** [comment]
@greg0ire done!

File: composer.json [hunk 34]
```diff
@@ -23,6 +23,7 @@
         "knplabs/gaufrette": "^0.1.6 || ^0.2 || ^0.3",
         "kriswallsmith/buzz": "^0.15",
         "psr/log": "^1.0",
+        "sensio/generator-bundle": "^3.1",
```
Comment (jlamur) [inline composer.json]: Why is this required?

File: Command/RemoveThumbsCommand.php [hunk 35]
```diff
@@ -127,12 +123,9 @@ public function execute(InputInterface $input, OutputInterface $output)
                     continue;
                 }
                 //clean filesystem registry for saving memory
-                $fsRegister->setValue($filesystem, []);
+                $provider->getFilesystem()->clearFileRegister();
             }
 
-            //clear entity manager for saving memory
-            $this->getMediaManager()->getEntityManager()->clear();
```
Comment (jlamur) [inline Command/RemoveThumbsCommand.php]: Why did you delete this line? I don't know if it effectivly saves memory or if it is safe. Is it the reason?

Maybe it won't work or it is useless if some media managers have a different entity manager?

Comment (vyshkant) [reply Command/RemoveThumbsCommand.php]: As of `"sonata-project/core-bundle": "^3.2"`, `Sonata\CoreBundle\Model\ManagerInterface` (which is returned by `$this->getMediaManager()` does not contain `getEntityManager` method.

**Comment by acrobat** [comment]
We are also running into this issue, our image stopped working when adding a new format and we are unable to run this command because we use symfony 3.3.

Is there any more work needed, I can help with this :)

**Comment by vyshkant** [comment]
@Soullivaneuh coud you please review this PR?

File: Command/RemoveThumbsCommand.php (hunk 35 above)
Comment (core23) [reply Command/RemoveThumbsCommand.php]: We should keep this line. Maybe add a `cleanup` method to the `MediaManager` to do the same.

**Comment by vyshkant** [comment]
> We should keep this line. Maybe add a cleanup method to the MediaManager to do the same.

What exactly should I do? Just keep this line, despite the fact that method `getEntityManager` may not exist? I think it's bad idea.

The `getEntityManager` method does not exist in `Sonata\CoreBundle\Model\ManagerInterface`, which is returned by `$this->getMediaManager()`.

It exists in `Sonata\CoreBundle\Model\BaseEntityManager`, the ancestor of `Sonata\MediaBundle\Entity\MediaManager`.

But `Sonata\CoreBundle\Model\BaseEntityManager` **does not** implement `Sonata\CoreBundle\Model\ManagerInterface` (which is returned by `$this->getMediaManager()`), while its child `Sonata\MediaBundle\Entity\MediaManager` does.

Adding new method to the interface will break BC, but I'm targeting `3.x` branch.

Based on all this, I think I should do next:

```php
if ($this->getMediaManager() instanceof \Sonata\CoreBundle\Model\BaseEntityManager) {
    $this->getMediaManager()->getEntityManager()->clear();
}
```
WDYT @core23 ?

**Comment by core23** [comment]
> What exactly should I do? Just keep this line, despite the fact that method getEntityManager may not exist? I think it's bad idea.

Create two PRs with the different things. This would make the merge process more transparent

**Comment by vyshkant** [comment]
> Create two PRs with the different things. This would make the merge process more transparent
I still don't get it.

Is this suitable for this PR?

```php
if ($this->getMediaManager() instanceof \Sonata\CoreBundle\Model\BaseEntityManager) {
    $this->getMediaManager()->getEntityManager()->clear();
}
```

**Comment by vyshkant** [comment]
Thank heaven!

File: composer.json (hunk 34 above)
Comment (jordisala1991) [reply composer.json]: Why is this required? If it is not used in the code we should remove it, it is causing some troubles, because it is not compatible with sf 4.0

@vyshkant

Comment (vyshkant) [reply composer.json]: @jordisala1991 As far as I remember, `sensio/generator-bundle` was required to use `Sensio\Bundle\GeneratorBundle\Command\Helper\QuestionHelper` and `Sensio\Bundle\GeneratorBundle\Command\Helper\DialogHelper` (see https://github.com/sonata-project/SonataMediaBundle/pull/1259#issuecomment-312598646).

But then we SUDDENLY found out that these classes are not used (see https://github.com/sonata-project/SonataMediaBundle/pull/1259#discussion_r144399174).

So now, I think, we can remove this dependency.
