### PR TITLE
make gaufrette config compatible with sf3

### LINKED ISSUE #987: [3.0] Unable to parse file gaufrette.xml
Hello my friends,

i've started a new project with symfony 3.0  and the mediabundle (dev-master) and run into an error 

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
Unable to parse file "/home/frank/masterarbeit/ecoin/vendor/sonata-project/media-bundle/DependencyInjection/../Resources/config/gaufrette.xml".  
                                                                                                                                                                                                         
[InvalidArgumentException]
[ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'factory-class': The attribute 'factory-class' is not allowed. (in /home/frank/masterarbeit/ecoin/ - line 16, column 0)

[ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'factory-method': The attribute 'factory-method' is not allowed. (in /home/frank/masterarbeit/ecoin/ - line 16, column 0)  

[ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'factory-service': The attribute 'factory-service' is not allowed. (in /home/frank/masterarbeit/ecoin/ - line 50, column  0)

[ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'factory-method': The attribute 'factory-method' is not allowed. (in /home/frank/masterarbeit/ecoin/ - line 50, column 0 )
```

Do you have any idea how i can fix this?

kind regards,
frank

### PR DESCRIPTION
**Pull request by hug963**
Closes #987

### Changelog

```markdown
### Fixed
- `gaufrette.xml` is now compatible with Symfony 3
```

### Subject

The Gaufrette configuration was using the deprecated functions setFactoryClass, setFactoryService and setFactoryMethod.

Fix source https://github.com/doctrine/DoctrineBundle/pull/381

### CODE REVIEW

File: DependencyInjection/SonataMediaExtension.php [hunk 1]
```diff
@@ -44,6 +44,27 @@ public function load(array $configs, ContainerBuilder $container)
         $loader->load('extra.xml');
         $loader->load('form.xml');
         $loader->load('gaufrette.xml');
+
+        $defS3 = $container->getDefinition('sonata.media.adapter.service.s3');
+        if (method_exists($defS3, 'setFactory')) {
+            // to be inlined in gaufrette.xml when dependency on Symfony is bumped to 2.6
```
Comment (greg0ire) [inline DependencyInjection/SonataMediaExtension.php]: Please use the `NEXT_MAJOR` label

File: DependencyInjection/SonataMediaExtension.php [hunk 2]
```diff
@@ -44,6 +44,27 @@ public function load(array $configs, ContainerBuilder $container)
         $loader->load('extra.xml');
         $loader->load('form.xml');
         $loader->load('gaufrette.xml');
+
+        $defS3 = $container->getDefinition('sonata.media.adapter.service.s3');
```
Comment (OskarStark) [inline DependencyInjection/SonataMediaExtension.php]: can we rename `$defS3`, this looks weird

Maybe `$amazonS3Definition` ??

/cc @greg0ire

File: DependencyInjection/SonataMediaExtension.php [hunk 3]
```diff
@@ -44,6 +44,27 @@ public function load(array $configs, ContainerBuilder $container)
...
+        if (method_exists($defS3, 'setFactory')) {
+            // NEXT_MAJOR: Inline in gaufrette.xml
```
Comment (OskarStark) [inline DependencyInjection/SonataMediaExtension.php]: please add the line to the gaufrette.xml and uncomment this and add a comment, to uncomment this in the next major, in this case we don't need the comment here 👍

File: DependencyInjection/SonataMediaExtension.php [hunk 4]
```diff
@@ -44,6 +44,27 @@ public function load(array $configs, ContainerBuilder $container)
...
+            $defS3->setFactory(array('Aws\S3\S3Client', 'factory'));
+        } else {
+            // NEXT_MAJOR: Remove
+            $defS3->setFactoryClass('Aws\S3\S3Client');
+            $defS3->setFactoryMethod('factory');
+        }
+
+        $defOpenCloud = $container->getDefinition('sonata.media.adapter.filesystem.opencloud.objectstore');
+        if (method_exists($defOpenCloud, 'setFactory')) {
+            // NEXT_MAJOR: Inline in gaufrette.xml
```
Comment (OskarStark) [inline DependencyInjection/SonataMediaExtension.php]: same as above

File: DependencyInjection/SonataMediaExtension.php [hunk 5]
```diff
@@ -44,6 +44,27 @@ public function load(array $configs, ContainerBuilder $container)
...
+        if (method_exists($defS3, 'setFactory')) {
+            // NEXT_MAJOR: Inline in gaufrette.xml
+            $defS3->setFactory(array('Aws\S3\S3Client', 'factory'));
+        } else {
+            // NEXT_MAJOR: Remove
+            $defS3->setFactoryClass('Aws\S3\S3Client');
+            $defS3->setFactoryMethod('factory');
+        }
+
+        $defOpenCloud = $container->getDefinition('sonata.media.adapter.filesystem.opencloud.objectstore');
```
Comment (OskarStark) [inline DependencyInjection/SonataMediaExtension.php]: can we rename `$defOpenCloud`, this looks weird

Maybe `$openCloudDefinition` ??

/cc @greg0ire

**Comment by OskarStark** [comment]
Thank you, i updated the changelog a bit!

Can you please apply my comments? Afterwards this LGTM 👍

**Comment by OskarStark** [comment]
`minor` or `patch` ?

`minor` i guess

File: DependencyInjection/SonataMediaExtension.php (hunk 3 above)
Comment (hug963) [inline DependencyInjection/SonataMediaExtension.php]: I'm not sure I got it right, I can have in gaufrette.xml: 

```xml
    <service id="sonata.media.adapter.service.s3" class="Aws\S3\S3Client">
        <!-- NEXT_MAJOR:  Uncomment Following line
        <factory class="Aws\S3\S3Client" method="factory" />
        -->
        <argument type="collection"/>
    </service>
```

and

```xml
    <service id="sonata.media.adapter.filesystem.opencloud.objectstore" class="OpenCloud\ObjectSource\Service">
        <!-- NEXT_MAJOR: Uncomment Following line 
        <factory service="sonata.media.adapter.filesystem.opencloud.connection" method="ObjectStore" />
        -->
        <argument/>
        <argument/>
    </service>
```

and the following in SonataMediaExtension.php:

```php
    // NEXT_MAJOR: Remove Following lines
    $amazonS3Definition = $container->getDefinition('sonata.media.adapter.service.s3');
    if (method_exists($amazonS3Definition, 'setFactory')) {
        $amazonS3Definition->setFactory(array('Aws\S3\S3Client', 'factory'));
    } else {
        $amazonS3Definition->setFactoryClass('Aws\S3\S3Client');
        $amazonS3Definition->setFactoryMethod('factory');
    }

    // NEXT_MAJOR: Remove Following lines
    $openCloudDefinition = $container->getDefinition('sonata.media.adapter.filesystem.opencloud.objectstore');
    if (method_exists($openCloudDefinition, 'setFactory')) {
        $openCloudDefinition->setFactory(array(new Reference('sonata.media.adapter.filesystem.opencloud.connection'), 'ObjectStore'));
    } else {
        $openCloudDefinition->setFactoryService('sonata.media.adapter.filesystem.opencloud.connection');
        $openCloudDefinition->setFactoryMethod('ObjectStore');
    }
```

Comment (OskarStark) [inline DependencyInjection/SonataMediaExtension.php]: LGTM 👍

**Comment by OskarStark** [comment]
@Soullivaneuh @greg0ire can you please give us a final review?

IMO its `RTM`

**Comment by greg0ire** [comment]
I'd say patch, because if you ask Composer, this bundle is already supposed to be compatible with sf3, so this is a bug.

**Comment by greg0ire** [comment]
Thanks @hug963 !

**Comment by OskarStark** [comment]
@hug963 would you provide a PR against `master` and remove the comments?

thank you!

**Comment by greg0ire** [comment]
@OskarStark : please don't ask that kind of PR until 3.x is merged into master, it shifts conflict resolution to the merger ( @Soullivaneuh )

**Comment by OskarStark** [comment]
> @OskarStark : please don't ask that kind of PR until 3.x is merged into master, it shifts conflict resolution to the merger ( @Soullivaneuh ) 

ofc you are totally right!

**Comment by xoeoro** [comment]
hello, could you add this patch to 3.0.x version of media bundle?

**Comment by Soullivaneuh** [comment]
@xoeoro It depends of the merged PR. If we have only patches, it will be a 3.0.1 release. If we have one or more minor, it will be a 3.1.0.
