### PR TITLE
Replace missing providers column by providerName on clean command

### LINKED ISSUE #1228: Clean command is using non existent field
### Environment
3x-dev
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.x-dev 7db5edb        The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.0                  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7                  Cache library
sonata-project/classification-bundle     3.x-dev 3d46e6a        Symfony SonataClassificationBundle
sonata-project/core-bundle               3.2.0                  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1                  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2                  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3                  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10                 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1                  Lightweight Exporter library
sonata-project/formatter-bundle          3.x-dev 77b45e5        Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.3.0                  Symfony SonataIntlBundle
sonata-project/media-bundle              3.x-dev 5189763        Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0                  Symfony SonataNotificationBundle

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle                   2.12.0                 Symfony MonologBundle
symfony/phpunit-bridge                   v3.2.1                 Symfony PHPUnit Bridge
symfony/polyfill-apcu                    v1.3.0                 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu                v1.3.0                 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring                v1.3.0                 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                   v1.3.0                 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                   v1.3.0                 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                    v1.3.0                 Symfony utilities for portability of PHP codes
symfony/security-acl                     v3.0.0                 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle               v2.4.2                 Symfony SwiftmailerBundle
symfony/symfony                          v3.1.8                 The Symfony PHP framework

#### PHP version

```bash
$ php -v
PHP 7.0.9 (cli) (built: Jul 21 2016 14:50:47) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
    with blackfire v1.14.2~mac-x64-non_zts70, https://blackfire.io, by Blackfireio Inc.

## Subject

 https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Command/CleanMediaCommand.php#L131

there should be providerName

## Steps to reproduce
./bin/console   sonata:media:clean-uploads 
## Expected results
no errors
## Actual results
Scanning upload directory:.../web/uploads/media
Context: destination
  [Doctrine\ORM\ORMException]    
  Unrecognized field: providers

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targeting this branch, because this a bugfix.

Closes #1228 #954 

## Changelog

```markdown
### Fixed
- Replace missing `providers` column by `providerName` on clean command
```

## Subject

Clean media command was not working because it was trying to access to a `providers` database column that does not exists. I Replaced it with `providerName`.

### CODE REVIEW

File: Command/CleanMediaCommand.php [hunk 1]
```diff
@@ -25,11 +25,6 @@
 class CleanMediaCommand extends ContainerAwareCommand
 {
     /**
-     * @var MediaProviderInterface[]|false
-     */
-    private $providers = false;
```
Comment (greg0ire) [inline Command/CleanMediaCommand.php]: > Clean media command was not working because it was trying to access to a providers property that does not exists.

I don't get it… looks like the property does exist, doesn't it?

File: Command/CleanMediaCommand.php [hunk 2]
```diff
@@ -121,14 +96,11 @@ private function mediaExists($filename, $context = null)
...
-                    'context' => $context,
-                )) != null;
+                'id' => $fileParts[1],
+                'context' => $context,
+            )) != null;
         }
 
-        return count($mediaManager->findBy(array(
-                'providerReference' => $filename,
-                'providers' => $this->getProviders(),
```
Comment (jordisala1991) [inline Command/CleanMediaCommand.php]: This line was causing the issue, the rest of the changes on this PR are just a refactor of removing this line:

- `$this->getProviders()` is no longer used
- verbosity was not handled correctly
- $providers private parameter is no longer needed

File: Command/CleanMediaCommand.php (hunk 1 above)
Comment (jordisala1991) [inline Command/CleanMediaCommand.php]: I changed a little bit the description, shall I move that description to the commit message body?

File: Command/CleanMediaCommand.php [hunk 3]
```diff
@@ -88,26 +83,6 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
-     */
-    private function getProviders()
-    {
-        if (!$this->providers) {
-            $this->providers = array();
-
-            $pool = $this->getContainer()->get('sonata.media.pool');
-
-            foreach ($pool->getProviders() as $provider) {
-                if ($provider instanceof FileProvider) {
```
Comment (greg0ire) [inline Command/CleanMediaCommand.php]: What about this restriction?

Comment (jordisala1991) [inline Command/CleanMediaCommand.php]: I guess this restriction is filtering to only keep FileProviders. This could be useful in case:

Have a file on the filesystem and when you findBy you get a Youtube (does not extends from FileProvider) with the same providerReference.

Maybe it needs to be kept?

File: Command/CleanMediaCommand.php (hunk 1 above)
Comment (greg0ire) [inline Command/CleanMediaCommand.php]: Yes. The commit message should let the reader understand : 

- what the issue was
- how you fixed it

File: Command/CleanMediaCommand.php (hunk 2 above)
Comment (greg0ire) [inline Command/CleanMediaCommand.php]: How was this working before?

Comment (jordisala1991) [inline Command/CleanMediaCommand.php]: Not really sure, this was implemented two years ago. https://github.com/sonata-project/SonataMediaBundle/pull/898

One year ago some guy just discover the bug, but the PR was never created.

I did look at the orm definition, but couldn't see any `providers` column (looking at all the modification of the columns)

Comment (greg0ire) [inline Command/CleanMediaCommand.php]: Same. No columns, no relationship… I don't get it. @core23 , can you help?

Comment (greg0ire) [inline Command/CleanMediaCommand.php]: Maybe this simply has never worked :/

**Comment by jordisala1991** [comment]
Applied all comments :)

**Comment by greg0ire** [comment]
Thanks @jordisala1991 !
