### PR TITLE
fixed provider metadata type error

### LINKED ISSUE #1531: Provider Metadata Type Error
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.45.1 3.45.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.14.0 3.14.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/classification-bundle     3.8.0  3.8.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.15.0 3.15.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5  1.1.5  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.0  3.8.0  Symfony Sonata / Integrate Doctrine ORM into the SonataA...
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.0.0  2.0.0  Lightweight Exporter library
sonata-project/media-bundle              3.18.0 3.18.0 Symfony SonataMediaBundle
sonata-project/user-bundle               4.2.3  4.2.3  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                v4.2.2  v4.2.2  Symfony Asset Component
symfony/browser-kit          v4.2.2  v4.2.2  Symfony BrowserKit Component
symfony/cache                v4.2.2  v4.2.2  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader         v3.4.21 v3.4.21 Symfony ClassLoader Component
symfony/config               v4.2.2  v4.2.2  Symfony Config Component
symfony/console              v4.2.2  v4.2.2  Symfony Console Component
symfony/contracts            v1.0.2  v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/css-selector         v3.4.21 v4.2.2  Symfony CssSelector Component
symfony/debug                v4.2.2  v4.2.2  Symfony Debug Component
symfony/debug-bundle         v4.2.2  v4.2.2  Symfony DebugBundle
symfony/debug-pack           v1.0.7  v1.0.7  A debug pack for Symfony projects
symfony/dependency-injection v4.2.2  v4.2.2  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.2.2  v4.2.2  Symfony Doctrine Bridge
symfony/dom-crawler          v4.2.2  v4.2.2  Symfony DomCrawler Component
symfony/dotenv               v4.2.2  v4.2.2  Registers environment variables from a .env file
symfony/event-dispatcher     v4.2.2  v4.2.2  Symfony EventDispatcher Component
symfony/expression-language  v4.2.2  v4.2.2  Symfony ExpressionLanguage Component
symfony/filesystem           v4.2.2  v4.2.2  Symfony Filesystem Component
symfony/finder               v4.2.2  v4.2.2  Symfony Finder Component
symfony/flex                 v1.1.8  v1.1.8  Composer plugin for Symfony
symfony/form                 v4.2.2  v4.2.2  Symfony Form Component
symfony/framework-bundle     v4.2.2  v4.2.2  Symfony FrameworkBundle
symfony/http-foundation      v4.2.2  v4.2.2  Symfony HttpFoundation Component
symfony/http-kernel          v4.2.2  v4.2.2  Symfony HttpKernel Component
symfony/inflector            v4.2.2  v4.2.2  Symfony Inflector Component
symfony/intl                 v4.2.2  v4.2.2  A PHP replacement layer for the C intl extension that includes add...
symfony/maker-bundle         v1.11.3 v1.11.3 Symfony Maker helps you create empty commands, controllers, form c...
symfony/monolog-bridge       v4.2.2  v4.2.2  Symfony Monolog Bridge
symfony/monolog-bundle       v3.3.1  v3.3.1  Symfony MonologBundle
symfony/options-resolver     v4.2.2  v4.2.2  Symfony OptionsResolver Component
symfony/orm-pack             v1.0.6  v1.0.6  A pack for the Doctrine ORM
symfony/panther              v0.2.0  v0.2.0  A browser testing and web scraping library for PHP and Symfony.
symfony/phpunit-bridge       v4.2.2  v4.2.2  Symfony PHPUnit Bridge
symfony/polyfill-ctype       v1.10.0 v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu    v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP v...
symfony/process              v4.2.2  v4.2.2  Symfony Process Component
symfony/profiler-pack        v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access      v4.2.2  v4.2.2  Symfony PropertyAccess Component
symfony/property-info        v4.2.2  v4.2.2  Symfony Property Info Component
symfony/routing              v4.2.2  v4.2.2  Symfony Routing Component
symfony/security-acl         v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.2.2  v4.2.2  Symfony SecurityBundle
symfony/security-core        v4.2.2  v4.2.2  Symfony Security Component - Core Library
symfony/security-csrf        v4.2.2  v4.2.2  Symfony Security Component - CSRF Library
symfony/security-guard       v4.2.2  v4.2.2  Symfony Security Component - Guard
symfony/security-http        v4.2.2  v4.2.2  Symfony Security Component - HTTP Integration
symfony/serializer           v4.2.2  v4.2.2  Symfony Serializer Component
symfony/serializer-pack      v1.0.2  v1.0.2  A pack for the Symfony serializer
symfony/stopwatch            v4.2.2  v4.2.2  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.5  v3.2.5  Symfony SwiftmailerBundle
symfony/templating           v4.2.2  v4.2.2  Symfony Templating Component
symfony/test-pack            v1.0.5  v1.0.5  A pack for functional and end-to-end testing within a Symfony app
symfony/translation          v4.2.2  v4.2.2  Symfony Translation Component
symfony/twig-bridge          v4.2.2  v4.2.2  Symfony Twig Bridge
symfony/twig-bundle          v4.2.2  v4.2.2  Symfony TwigBundle
symfony/validator            v4.2.2  v4.2.2  Symfony Validator Component
symfony/var-dumper           v4.2.2  v4.2.2  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter         v4.2.2  v4.2.2  A blend of var_export() + serialize() to turn any serializable dat...
symfony/web-link             v4.2.2  v4.2.2  Symfony WebLink Component
symfony/web-profiler-bundle  v4.2.2  v4.2.2  Symfony WebProfilerBundle
symfony/web-server-bundle    v4.2.2  v4.2.2  Symfony WebServerBundle
symfony/webpack-encore-pack  v1.0.3  v1.0.3  A pack for Symfony Encore
symfony/yaml                 v4.2.2  v4.2.2  Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.2.12 (cli) (built: Nov 16 2018 03:34:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```

## Subject
Sonata Provider Type Error 

## Steps to reproduce
* Update to latest sonata media bundle version
* try to upload a media => select provider page it happens

## Actual results

bildschirmfoto 2019-01-20 um 18 33 19

### PR DESCRIPTION
**Pull request by silasjoisten**
## Subject
Fixed Type Error 
closes #1531 

bildschirmfoto 2019-01-20 um 18 33 19

I am targeting this branch, because this is a bc.

```markdown
### Fixed
- Providers Type Error.
```

After that fix the `select_provider.html.twig` was unable to check if it should use icon or image.
bildschirmfoto 2019-01-20 um 18 43 26

* Fix for that is to allow getImage() can return null and no default image gets set in constuctor

### CODE REVIEW

File: src/Provider/FileProvider.php [hunk 1]
```diff
@@ -67,7 +67,7 @@ public function __construct($name, Filesystem $filesystem, CDNInterface $cdn, Ge
      */
     public function getProviderMetadata()
     {
-        return new Metadata($this->getName(), $this->getName().'.description', false, 'SonataMediaBundle', ['class' => 'fa fa-file-text-o']);
+        return new Metadata($this->getName(), $this->getName().'.description', null, 'SonataMediaBundle', ['class' => 'fa fa-file-text-o']);
```
Comment (greg0ire) [inline src/Provider/FileProvider.php]:
```suggestion
        return new Metadata(
            $this->getName(),
            $this->getName().'.description',
            null,
            'SonataMediaBundle',
            ['class' => 'fa fa-file-text-o']
        );
```

File: src/Provider/ImageProvider.php [hunk 2]
```diff
@@ -53,7 +53,7 @@ public function __construct($name, Filesystem $filesystem, CDNInterface $cdn, Ge
      */
     public function getProviderMetadata()
     {
-        return new Metadata($this->getName(), $this->getName().'.description', false, 'SonataMediaBundle', ['class' => 'fa fa-picture-o']);
+        return new Metadata($this->getName(), $this->getName().'.description', null, 'SonataMediaBundle', ['class' => 'fa fa-picture-o']);
```
Comment (greg0ire) [inline src/Provider/ImageProvider.php]:
```suggestion
        return new Metadata(
            $this->getName(),
            $this->getName().'.description',
            null,
            'SonataMediaBundle',
            ['class' => 'fa fa-picture-o']
        );
```

File: src/Provider/Metadata.php [hunk 3]
```diff
@@ -52,7 +52,7 @@ public function __construct(
...
+        $this->image = $image;
```
Comment (greg0ire) [inline src/Provider/Metadata.php]: Why did you change this?

File: src/Provider/VimeoProvider.php [hunk 4]
```diff
@@ -79,7 +79,7 @@ public function getHelperProperties(MediaInterface $media, $format, $options = [
      */
     public function getProviderMetadata()
     {
-        return new Metadata($this->getName(), $this->getName().'.description', false, 'SonataMediaBundle', ['class' => 'fa fa-vimeo-square']);
+        return new Metadata($this->getName(), $this->getName().'.description', null, 'SonataMediaBundle', ['class' => 'fa fa-vimeo-square']);
```
Comment (greg0ire) [inline src/Provider/VimeoProvider.php]:
```suggestion
        return new Metadata(
            $this->getName(),
            $this->getName().'.description',
            null,
            'SonataMediaBundle',
            ['class' => 'fa fa-vimeo-square']
        );
```

File: src/Provider/YouTubeProvider.php [hunk 5]
```diff
@@ -50,7 +50,7 @@ public function __construct($name, Filesystem $filesystem, CDNInterface $cdn, Ge
      */
     public function getProviderMetadata()
     {
-        return new Metadata($this->getName(), $this->getName().'.description', false, 'SonataMediaBundle', ['class' => 'fa fa-youtube']);
+        return new Metadata($this->getName(), $this->getName().'.description', null, 'SonataMediaBundle', ['class' => 'fa fa-youtube']);
```
Comment (greg0ire) [inline src/Provider/YouTubeProvider.php]:
```suggestion
        return new Metadata(
            $this->getName(),
            $this->getName().'.description',
            null,
            'SonataMediaBundle',
            ['class' => 'fa fa-youtube']
        );
```

File: src/Provider/Metadata.php (hunk 3 above)
Comment (silasjoisten) [reply src/Provider/Metadata.php]: That will happen when its a fallback string:
bildschirmfoto 2019-01-20 um 18 43 26

Comment (greg0ire) [reply src/Provider/Metadata.php]: cc @jo66 please help

Comment (silasjoisten) [reply src/Provider/Metadata.php]: We need to allow null here, otherwise in the template `select_provider.html.twig:32`
```twig
{% if not provider.providerMetadata.image %}
    <i class="{{ provider.providerMetadata.option('class') }}"></i>
{% else %}
    <img src="{{ asset(provider.providerMetadata.image) }}" style="max-height: 20px; max-width: 100px;"/><br />
{% endif %}

```

Comment (silasjoisten) [reply src/Provider/Metadata.php]: okay shall i change it?

Comment (jo66) [reply src/Provider/Metadata.php]: I guess it's better to keep image not null, so yes.

**Comment by mohamedyasser** [comment]
@greg0ire @jo66 @silasjoisten 
why it's not merged I'm just created a new project I will downgrade to 3.16
