### PR TITLE
Remove dependency of classification-bundle

### LINKED ISSUE #783: Sonata Classification manager problem
Hi I have problem with adding sonata media bundle, after I add and configure , there is problem with some service.

Any help on this?

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  The service "sonata.media.admin.media" has a dependency on a non-existent service "sonata.classification.manager.category".

### PR DESCRIPTION
**Pull request by core23**
I am targetting this branch, because it removes existing functionality.

Rebase of #794
Closes #783 #684

## Changelog

```markdown
### Added
- Added option to disable classification

### Changed
 - made `sonata-project/classification-bundle` dependency optional
```

## Subject

This is a rebase of https://github.com/sonata-project/SonataMediaBundle/pull/794, because there was no further interaction. 

This PR made the classifcation dependency optional.

### CODE REVIEW

File: Admin/BaseMediaAdmin.php [hunk 1]
```diff
@@ -38,8 +38,13 @@
      * @param Pool                     $pool
      * @param CategoryManagerInterface $categoryManager
      */
-    public function __construct($code, $class, $baseControllerName, Pool $pool, CategoryManagerInterface $categoryManager)
-    {
+    public function __construct(
```
Comment (OskarStark) [inline Admin/BaseMediaAdmin.php]: No linebreak please

File: Model/CategoryManager.php [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Sonata\MediaBundle\Model;
+
+use Sonata\ClassificationBundle\Model\CategoryManagerInterface as ManagerInterface;
+
+final class CategoryManager implements CategoryManagerInterface
```
Comment (OskarStark) [inline Model/CategoryManager.php]: @author missing

File: Model/CategoryManagerInterface.php [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+ * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Sonata\MediaBundle\Model;
+
+use Sonata\ClassificationBundle\Model\CategoryInterface;
+
```
Comment (OskarStark) [inline Model/CategoryManagerInterface.php]: @author missing

File: Tests/DependencyInjection/SonataMediaExtensionTest.php [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+        $container = $this->getContainer();
+
+        $this->assertFalse($container->hasDefinition('sonata.media.manager.category'));
+    }
+
+    public function testLoadWithDefaultAndCustomCategoryManager()
+    {
+        $container = $this->getContainer(
+            array(array(
+            'class'            => array('category' => '\stdClass'),
```
Comment (OskarStark) [inline Tests/DependencyInjection/SonataMediaExtensionTest.php]: Wrong CS

File: Model/CategoryManagerInterface.php (hunk 3 above)
Comment (core23) [inline Model/CategoryManagerInterface.php]: I added you as an author @Trip09

**Comment by core23** [comment]
- Removed dev dependency too
- Created classification fixture

**Comment by core23** [comment]
Please review @greg0ire @Soullivaneuh

**Comment by Soullivaneuh** [comment]
So no chance to have this BC?

File: Command/FixMediaContextCommand.php [hunk 5]
```diff
@@ -32,9 +32,17 @@ public function configure()
      */
     public function execute(InputInterface $input, OutputInterface $output)
     {
+        if (false === $this->getContainer()->has('sonata.media.manager.category')) {
```
Comment (greg0ire) [inline Command/FixMediaContextCommand.php]: Use `!$this->getContainer()->has('sonata.media.manager.category')`. This method will always return a boolean.

**Comment by core23** [comment]
> So no chance to have this BC?

We can't REMOVE the dependency, because this is a break. The only thing that could be done is adding a new layer to all locaction where we refer to a category manager.

File: Command/FixMediaContextCommand.php [hunk 6]
```diff
@@ -32,9 +32,17 @@ public function configure()
...
+            throw new \LogicException('The classification feature is disabled.');
+        }
+
+        if (false === $this->getContainer()->has('sonata.classification.manager.context')) {
+            throw new \LogicException('There is no sonata.classification.manager.context defined.');
+        }
```
Comment (greg0ire) [inline Command/FixMediaContextCommand.php]: How is this better than the built-in exception message you will get?

File: DependencyInjection/Configuration.php [hunk 7]
```diff
@@ -34,6 +34,14 @@ public function getConfigTreeBuilder()
             ->children()
                 ->scalarNode('db_driver')->isRequired()->end()
                 ->scalarNode('default_context')->isRequired()->end()
+                ->scalarNode('category_manager')
+                    ->info('if sonata-project/classification exists will set "sonata.classification.manager.category" or if you want to define your own category manager you need to implement \Sonata\MediaBundle\Model\CategoryManagerInterface and set the service name here')
```
Comment (greg0ire) [inline DependencyInjection/Configuration.php]: Please linebreak this

File: DependencyInjection/SonataMediaExtension.php [hunk 8]
```diff
@@ -533,4 +538,42 @@ public function configureClassesToCompile()
...
+    /**
+     * Checks if the classification of media is enabled.
+     *
+     * @param array $config
+     *
+     * @return bool
+     */
+    private function isClassificationEnabled(array $config)
+    {
+        return false === $config['force_disable_category'] &&
```
Comment (greg0ire) [inline DependencyInjection/SonataMediaExtension.php]: It's a boolean node, please use `!$config['force_disable_category']`

File: DependencyInjection/Configuration.php (hunk 7 above)
Comment (Soullivaneuh) [inline DependencyInjection/Configuration.php]: It will be better to shorten the sentence.

This is used for `config:dump-reference` command.

Comment (Soullivaneuh) [inline DependencyInjection/Configuration.php]: BTW it would be great to not linebreak on configuration.

Thoses classes has a specific indentation, it will be hard to read with linebreaking.

If we have to much indentation, then we should consider separate configuration part onto private methods.

File: Resources/views/MediaAdmin/list.html.twig [hunk 9]
```diff
@@ -35,9 +35,11 @@ file that was distributed with this source code.
 {% endmacro %}
 
 {% block list_table %}
+    {% if datagrid.values['category'] is defined and datagrid.values['category']['value'] is defined %}
```
Comment (greg0ire) [inline Resources/views/MediaAdmin/list.html.twig]: Are both check really needed?

File: UPGRADE-4.0.md [hunk 10]
```diff
@@ -21,3 +21,7 @@ If you have implemented a custom model, you must adapt the signature of the foll
 ## Renamed GalleryHasMedia to GalleryItem
 
 All Actions, Controllers, Interfaces and anything related to this is renamed accordingly.
+
+## Removed classification dependency
+
+The category features is now optional and can be disabled in the configuration. If you need this feature you have to require `sonata-project/classifcation-bundle` via composer.
```
Comment (greg0ire) [inline UPGRADE-4.0.md]: "features" = "feature"

File: Resources/views/MediaAdmin/list.html.twig (hunk 9 above)
Comment (core23) [inline Resources/views/MediaAdmin/list.html.twig]: Yes, otherwise you will get a twig error

Comment (greg0ire) [inline Resources/views/MediaAdmin/list.html.twig]: Have you actually tested that? I'm asking because I believe `is defined` might act like `isset`, and here is how `isset` behaves : 

```
Interactive mode enabled

php > $a = [];
php > var_dump(isset($a['does']['not']['exist']));
bool(false)
```

Comment (greg0ire) [inline Resources/views/MediaAdmin/list.html.twig]: Oh wow twigfiddle exists. [And I don't think the check is required](http://twigfiddle.com/xqfvu6)

Comment (core23) [inline Resources/views/MediaAdmin/list.html.twig]: twigfiddle? Wtf? There's an app for that! :trollface:

Thought that was an error, but never tried ^^

File: Command/FixMediaContextCommand.php [hunk 11]
```diff
@@ -52,17 +56,17 @@ public function execute(InputInterface $input, OutputInterface $output)
                 $contextManager->save($defaultContext);
             }
 
-            $defaultCategory = $cateoryManager->getRootCategory($defaultContext);
+            $defaultCategory = $categoryManager->getRootCategory($defaultContext);
 
             if (!$defaultCategory) {
                 $output->writeln(sprintf(" > default category for '%s' is missing, creating one", $context));
-                $defaultCategory = $cateoryManager->create();
+                $defaultCategory = $categoryManager->create();
```
Comment (greg0ire) [inline Command/FixMediaContextCommand.php]: In rare cases like this, auto-completion is a bad thing :P

File: DependencyInjection/SonataMediaExtension.php [hunk 12]
```diff
@@ -533,4 +538,40 @@ public function configureClassesToCompile()
...
+    {
+        if (!$this->isClassificationEnabled($config)) {
+            return;
+        }
+
+        if (null !== $config['category_manager']) {
+            $container->setAlias('sonata.media.manager.category', $config['category_manager']);
+        } else {
+            $container->setAlias('sonata.media.manager.category', 'sonata.media.manager.category.default');
+        }
```
Comment (greg0ire) [inline DependencyInjection/SonataMediaExtension.php]: `$container->setAlias(
    'sonata.media.manager.category', 
    $config['category_manager'] ?: 'sonata.media.manager.category.default'
);`

File: DependencyInjection/Configuration.php [hunk 13]
```diff
@@ -34,6 +34,14 @@ public function getConfigTreeBuilder()
             ->children()
                 ->scalarNode('db_driver')->isRequired()->end()
                 ->scalarNode('default_context')->isRequired()->end()
+                ->scalarNode('category_manager')
+                    ->info('null or "sonata.media.manager.category.default" if classification bundle exists')
```
Comment (greg0ire) [inline DependencyInjection/Configuration.php]: "if classification bundle is enabled"

File: Tests/DependencyInjection/SonataMediaExtensionTest.php [hunk 14]
```diff
@@ -0,0 +1,105 @@
...
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\DependencyInjection\Definition;
+
+class SonataMediaExtensionTest extends \PHPUnit_Framework_TestCase
+{
+    public function testLoadWithDefaultNoClassificationBundle()
+    {
+        $container = $this->getContainer();
+
+        $this->assertFalse($container->hasDefinition('sonata.media.manager.category'));
```
Comment (greg0ire) [inline Tests/DependencyInjection/SonataMediaExtensionTest.php]: `$container` is an OTV, seems unneeded.

File: Tests/fixtures/classification.php [hunk 15]
```diff
@@ -0,0 +1,38 @@
...
+    public function setId($id);
+
+    public function setName($name);
+
+    public function setEnabled($enabled);
+}
+
+interface ContextManagerInterface extends ManagerInterface
+{
+}
```
Comment (greg0ire) [inline Tests/fixtures/classification.php]: Please use PSR-4 autoloading

File: UPGRADE-4.0.md [hunk 16]
```diff
@@ -21,3 +21,7 @@ If you have implemented a custom model, you must adapt the signature of the foll
 ## Renamed GalleryHasMedia to GalleryItem
 
 All Actions, Controllers, Interfaces and anything related to this is renamed accordingly.
+
+## Removed classification dependency
+
+The category feature is now optional and can be disabled in the configuration. If you need this feature you have to require `sonata-project/classifcation-bundle` via composer.
```
Comment (greg0ire) [inline UPGRADE-4.0.md]: Please linebreak this.

File: Tests/fixtures/classification.php (hunk 15 above)
Comment (core23) [inline Tests/fixtures/classification.php]: We have a different namespace here, so we need some kind of hack.

Comment (greg0ire) [inline Tests/fixtures/classification.php]: Oh right, that's a bit weird, but… can be done by simply tweaking the `autoload-dev` key, right?

Comment (core23) [inline Tests/fixtures/classification.php]: Fixed that

File: composer.json [hunk 17]
```diff
@@ -78,7 +79,10 @@
         ]
     },
     "autoload-dev": {
-        "psr-4": { "Sonata\\MediaBundle\\Tests\\": "Tests/" }
+        "psr-4": {
+            "Sonata\\MediaBundle\\Tests\\": "Tests/",
+            "Sonata\\ClassificationBundle\\": "Tests/fixtures/SonataClassificationBundle"
```
Comment (greg0ire) [inline composer.json]: Great job!

**Comment by greg0ire** [comment]
LGTM

**Comment by core23** [comment]
Please have a look at this @sonata-project/contributors

**Comment by ruscon** [comment]
ping ?

File: DependencyInjection/Configuration.php [hunk 18]
```diff
@@ -34,6 +34,14 @@ public function getConfigTreeBuilder()
             ->children()
                 ->scalarNode('db_driver')->isRequired()->end()
                 ->scalarNode('default_context')->isRequired()->end()
+                ->scalarNode('category_manager')
+                    ->info('null or "sonata.media.manager.category.default" if classification bundle is enabled')
+                    ->defaultValue(null)
+                ->end()
+                ->booleanNode('force_disable_category')
+                    ->info('true IF you really want to disable the relation with category')
+                    ->defaultValue(false)
```
Comment (OskarStark) [inline DependencyInjection/Configuration.php]: is `->defaultFalse()` available here?

File: DependencyInjection/Configuration.php [hunk 19]
```diff
@@ -34,6 +34,14 @@ public function getConfigTreeBuilder()
             ->children()
                 ->scalarNode('db_driver')->isRequired()->end()
                 ->scalarNode('default_context')->isRequired()->end()
+                ->scalarNode('category_manager')
+                    ->info('null or "sonata.media.manager.category.default" if classification bundle is enabled')
+                    ->defaultValue(null)
```
Comment (OskarStark) [inline DependencyInjection/Configuration.php]: is `->defaultNull()` available

File: DependencyInjection/Configuration.php [hunk 20]
```diff
@@ -418,7 +426,10 @@ private function addModelSection(ArrayNodeDefinition $node)
                         ->scalarNode('media')->defaultValue('Application\\Sonata\\MediaBundle\\Entity\\Media')->end()
                         ->scalarNode('gallery')->defaultValue('Application\\Sonata\\MediaBundle\\Entity\\Gallery')->end()
                         ->scalarNode('gallery_item')->defaultValue('Application\\Sonata\\MediaBundle\\Entity\\GalleryItem')->end()
-                        ->scalarNode('category')->defaultValue('Application\\Sonata\\ClassificationBundle\\Entity\\Category')->end()
+                        ->scalarNode('category')
+                            ->info('null or Application\Sonata\ClassificationBundle\Entity\Category if exists')
+                            ->defaultValue(null)
```
Comment (OskarStark) [inline DependencyInjection/Configuration.php]: same here?

File: Model/Media.php [hunk 21]
```diff
@@ -641,7 +641,7 @@ public function getCategory()
     }
 
     /**
-     * @param CategoryInterface $category|null
+     * @param CategoryInterface|null $category
```
Comment (OskarStark) [inline Model/Media.php]: good catch 👍

File: composer.json [hunk 22]
```diff
@@ -59,6 +58,7 @@
         "sllh/php-cs-fixer-styleci-bridge": "^2.0"
     },
     "suggest": {
+        "sonata-project/classification-bundle": "For classification of media items",
```
Comment (OskarStark) [inline composer.json]: `If you want to use categorize your media items.`

**Comment by OskarStark** [comment]
LGTM 👍

**Comment by meandus** [comment]
When it will be pushed ??

**Comment by greg0ire** [comment]
Thanks @core23 

@meandus : this is to the master branch, so it will be quite hard to get before sonata 4 is released.

**Comment by meandus** [comment]
I can put master branch for MediaBundle but there is no modification for this pull request.

**Comment by greg0ire** [comment]
There might be some delay. Check the commit hash.

**Comment by meandus** [comment]
Catchable Fatal Error: Argument 1 passed to Sonata\MediaBundle\Model\CategoryManager::__construct() must be an instance of Sonata\ClassificationBundle\Model\CategoryManagerInterface, null given

**Comment by meandus** [comment]
sorry, forgot force_disable_category: true

**Comment by jenyak** [comment]
The type hint of parameter "category" in method "setCategory" in class "Application\Sonata\MediaBundle\Entity\Media" is invalid
Class Sonata\ClassificationBundle\Model\CategoryInterface does not exist

File: Model/CategoryManagerInterface.php [hunk 23]
```diff
@@ -0,0 +1,63 @@
...
+{
+    /**
+     * @param string $context
+     *
+     * @return CategoryInterface
+     */
+    public function getRootCategory($context);
+
+    /**
+     * @param bool|true $loadChildren
```
Comment (OskarStark) [inline Model/CategoryManagerInterface.php]: is `bool|true` valid phpdoc?

Comment (greg0ire) [inline Model/CategoryManagerInterface.php]: … and if it is, what the hell does that mean?

Comment (lemoinem) [inline Model/CategoryManagerInterface.php]: AFAIK, It is valid phpdoc (https://phpdoc.org/docs/latest/guides/types.html, `bool` and `true` are both valid types), and it means the parameter is a boolean with default value `true`

Comment (greg0ire) [inline Model/CategoryManagerInterface.php]: I don't think the pipe is used to mean that… usually , it is used to list possible types (a mixed type)

Comment (lemoinem) [inline Model/CategoryManagerInterface.php]: Indeed, but I've seen several people use it to specify special/default values. Mostly with `|null` or for return values (that case is even explicitly mentioned in the doc).

Comment (greg0ire) [inline Model/CategoryManagerInterface.php]: I'd argue that [`null` is a type](http://php.net/manual/en/language.types.null.php). `true` is not. The link you provided says it can be used to indicate when a method always returns `true`, but that's all…

**Comment by jenyak** [comment]
Can we just remove type hint in [setCategory](https://github.com/sonata-project/SonataMediaBundle/blob/master/Model/Media.php#L646) or there must be another solution?

**Comment by core23** [comment]
> The type hint of parameter "category" in method "setCategory" in class "Application\Sonata\MediaBundle\Entity\Media" is invalid
> Class Sonata\ClassificationBundle\Model\CategoryInterface does not exist

That's just a local class in your project.

**Comment by jenyak** [comment]
Yes, but it is extends `Sonata\MediaBundle\Entity\BaseMedia` which extends `Sonata\MediaBundle\Model\Media`

**Comment by desarrolla2** [comment]
there are a lot of references of sonata.classification.manager.category  service in sonata media bundle
