### PR TITLE
Fix providerName access from request object

### LINKED ISSUE #1197: Illegal string offset 'providerName' in BaseMediaAdmin
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.13.0          The missing Symfon...
sonata-project/block-bundle              3.3.0           Symfony SonataBloc...
sonata-project/cache                     1.0.7           Cache library
sonata-project/classification-bundle     3.x-dev bb93897 Symfony SonataClas...
sonata-project/core-bundle               3.2.0           Symfony SonataCore...
sonata-project/datagrid-bundle           2.2.1           Symfony SonataData...
sonata-project/doctrine-extensions       1.0.2           Doctrine2 behavior...
sonata-project/doctrine-orm-admin-bundle 3.x-dev 674fbad Symfony Sonata / I...
sonata-project/easy-extends-bundle       2.1.10          Symfony SonataEasy...
sonata-project/exporter                  1.7.1           Lightweight Export...
sonata-project/intl-bundle               2.3.0           Symfony SonataIntl...
sonata-project/media-bundle              3.x-dev 07b2179 Symfony SonataMedi...
sonata-project/notification-bundle       3.1.0           Symfony SonataNoti...
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* func...
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related ...
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5....
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5....
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5....
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7....
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP...
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access...
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.17 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.15 (cli) (built: Jan 20 2017 06:03:19) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

## Subject

providerName is not correctly being read from the request because of a misplaced parenthesis.

## Steps to reproduce

Upload an image from SonataAdmin panel using SonataMediaBundle 3.x with Symfony <= 2.8

## Expected results

Correct image upload.

## Actual results

Warning: Illegal string offset 'providerName' in vendor/sonata-project/media-bundle/Admin/BaseMediaAdmin.php at line 118

### PR DESCRIPTION
**Pull request by enekochan**
BaseMediaAdmin incorrectly retrieved providerName from request

I am targeting this branch, because the bug was recently introduced in it in this PR #1191

Closes #1197

## Changelog

```markdown
### Fixed
- Incorrect access to providerName parameter in request in `Admin/BaseMediaAdmin.php`
```

## Subject

This fixes a recently introduced bug where the providerName was incorrectly being read from the request object.

### CODE REVIEW

**Comment by greg0ire** [comment]
@jordisala1991 can you review this?

**Comment by jordisala1991** [comment]
I was using the code you provided on: https://github.com/sonata-project/SonataMediaBundle/pull/1148#discussion_r89662271

We could add some test to this method now. The test class is already there.

**Comment by greg0ire** [comment]
Are you ok with @enekochan 's PR though?

**Comment by jordisala1991** [comment]
I'm okay with it.

I can do a pull request to your repo @enekochan, but will be tonight.

File: Admin/BaseMediaAdmin.php [hunk 1]
```diff
@@ -115,7 +115,7 @@ public function getNewInstance()
                     );
                 } else {
                     $media->setProviderName(
-                        $this->getRequest()->get($uniqid['providerName'])
+                        $this->getRequest()->get($uniqid)['providerName']
```
Comment (greg0ire) [inline Admin/BaseMediaAdmin.php]: Function array dereferencing does not work on old versions of php, you will have to change that (that's why the build fails)

**Comment by greg0ire** [comment]
Next time just amend and force push @enekochan : no one needs to know you used FAD ;)

File: Admin/BaseMediaAdmin.php [hunk 2]
```diff
@@ -114,8 +114,9 @@ public function getNewInstance()
                         $this->getRequest()->get(sprintf('%s[providerName]', $uniqid), null, true)
                     );
                 } else {
+                    $provider = $this->getRequest()->get($uniqid);
                     $media->setProviderName(
-                        $this->getRequest()->get($uniqid['providerName'])
+                        $provider['providerName']
```
Comment (jordisala1991) [inline Admin/BaseMediaAdmin.php]: Now it can be single line.

File: Admin/BaseMediaAdmin.php [hunk 3]
```diff
@@ -114,8 +114,9 @@ public function getNewInstance()
                         $this->getRequest()->get(sprintf('%s[providerName]', $uniqid), null, true)
                     );
                 } else {
+                    $provider = $this->getRequest()->get($uniqid);
```
Comment (OskarStark) [inline Admin/BaseMediaAdmin.php]: $provider is wrong IMO, at least confusing

Comment (enekochan) [inline Admin/BaseMediaAdmin.php]: What name would you propose? It really is wrong because that array is not just about the provider as I thought. When I debugged it before the content was something like this:

```
request = {Symfony\Component\HttpFoundation\ParameterBag} [1]
    parameters = {array} [2]
        s58a1...73 = {array} [3]
            providerName = "sonata.media.provider.image"
            category = "3"
            _token = "7lBh...0rc"
        _xml_http_request = "true"
```

Comment (greg0ire) [inline Admin/BaseMediaAdmin.php]: `$providerParams` ?

Comment (jordisala1991) [inline Admin/BaseMediaAdmin.php]: Then it is not ['providerName'] but ->get('providerName') right?

Comment (greg0ire) [inline Admin/BaseMediaAdmin.php]: `ParameterBag` implements `\IteratorAggregate`, so both should work.

Comment (enekochan) [inline Admin/BaseMediaAdmin.php]: Sorry the mess up with the commits, I'm not that good with git :(

Comment (greg0ire) [inline Admin/BaseMediaAdmin.php]: No problem, we'll be able to fix it.

**Comment by jordisala1991** [comment]
Perfect, thanks @enekochan. Will provide some test tonight if I have time.

**Comment by jordisala1991** [comment]
Can we just change from:

```
$uniqid = $this->getUniqid();

if (method_exists('Symfony\Component\HttpFoundation\JsonResponse', 'transformJsonError')) {
    // NEXT_MAJOR remove this block when dropping sf < 2.8 compatibility
    $media->setProviderName(
        $this->getRequest()->get(sprintf('%s[providerName]', $uniqid), null, true)
    );
} else {
    $providerParams = $this->getRequest()->get($uniqid);
    $media->setProviderName($providerParams['providerName']);
}
```

to:

```
$providerParams = $this->getRequest()->get($this->getUniqid());
$media->setProviderName($providerParams['providerName']);
```

**Comment by greg0ire** [comment]
You mean drop < 2.8 compatibility?

**Comment by jordisala1991** [comment]
The second code is incompatible with SF2.3?

**Comment by greg0ire** [comment]
Looks like it…

**Comment by jordisala1991** [comment]
Then I did say nothing xD

**Comment by jordisala1991** [comment]
https://github.com/enekochan/SonataMediaBundle/pull/1

This should cover this code... those test are very fragile really... could you please review @greg0ire @enekochan ?

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

**Comment by OskarStark** [comment]
@greg0ire shall we merge it with a merge commit? because there is already the merge commit of @enekochan ...

**Comment by greg0ire** [comment]
No, the tests shouldn't live w/o the code (and vice versa,  hopefully), so let's just squash. Thanks @enekochan @jordisala1991 !

**Comment by OskarStark** [comment]
Great teamwork 👍

**Comment by enekochan** [comment]
Thanks to you all :) I'm glad I could contribute.
