### PR TITLE
Make a db_driver configuration parameter optional with no_driver default value

### LINKED ISSUE #1419: [Proposal] A recipe for Symfony Flex
The main blocker for recipe is a `db_driver` parameter - it is required and it's possible values cannot be used without installing additional packages.

We could make that parameter optional with `no_driver` default value, like i suggested in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2708. The main goal of a default value is to pass `cache:clear` stage without errors and to make a recipe valid.

With a new driver some services like `sonata.media.manager.media` must be created, because other services depend on them. I suggest to create a new classes for that services, that will throw exceptions on usage _in runtime_ with instructions for a developer what to do next.

With a default `db_driver` we will have a recipe with default configuration for MediaBundle. This configuration will be extended by recipes for specific meta package, i.e. `sonata-project/media-orm-pack` or `sonata-project/media-phpcr-pack`. All such packages will require `sonata-project/media-bundle` and conflict with each other. Each pack recipe will contain only Entity, Document or PHPCR classes _with annotations_, that will be copied into `src` directory during installation. So, no new `maker` or `easy-extends` bundle will be required.

### PR DESCRIPTION
**Pull request by covex-nn**
I am targeting this branch, because this is BC.

Closes #1419

## Changelog

```markdown
### Changed
- A db_driver configuration parameter is optional now with 'no_driver' default value
```

## To do

- [x] Add tests

## Subject

To create a recipe for Symfony Flex, it should be possible to create a default configuration, that allows to run `cache:clear` without errors (see https://github.com/sonata-project/dev-kit/issues/409) A default value for `db_driver` configuration parameter will allow this.

If this PR will be accepted, a default configuration, i.e. a recipe for `sonata-media/media-bundle` could be like this (please fix me, it there something wrong here; may be `providers` or `formats` sections should be changed to more commonly used?):

```yaml
sonata_media:
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            directory: "%kernel.project_dir%/public/upload/media"
            create: false
```

Additional configuration, i.e. a recipe for a new package `sonata-project/media-orm-pack` could be like this (i created a [gist](https://gist.github.com/covex-nn/76795ddb85fb3656d716e462a748156c) with entity classes):

```yaml
sonata_media:
    class:
        media: App\Entity\SonataMediaMedia
        gallery: App\Entity\SonataMediaGallery
        gallery_has_media: App\Entity\SonataMediaGalleryHasMedia
    db_driver: doctrine_orm
```

### CODE REVIEW

File: src/Generator/NoDriverGenerator.php [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Sonata\MediaBundle\Generator;
+
+use Sonata\MediaBundle\Model\MediaInterface;
+use Sonata\MediaBundle\SonataMediaBundle;
+
```
Comment (kunicmarko20) [inline src/Generator/NoDriverGenerator.php]: `@author` is missing

File: src/Model/NoDriverManager.php [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+
+namespace Sonata\MediaBundle\Model;
+
+use Sonata\CoreBundle\Model\ManagerInterface;
+use Sonata\MediaBundle\SonataMediaBundle;
+
+/**
+ * @internal
+ */
+class NoDriverManager implements ManagerInterface
```
Comment (kunicmarko20) [inline src/Model/NoDriverManager.php]: `@author`

File: src/Model/NoDriverManager.php [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+    {
+        SonataMediaBundle::noDriverRuntimeException();
+    }
+
+    public function findAll()
+    {
+        SonataMediaBundle::noDriverRuntimeException();
+    }
+
+    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
```
Comment (kunicmarko20) [inline src/Model/NoDriverManager.php]: please add comments about `types` of vars

File: src/Model/NoDriverManager.php [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+    {
+        SonataMediaBundle::noDriverRuntimeException();
+    }
+
+    public function findOneBy(array $criteria, array $orderBy = null)
+    {
+        SonataMediaBundle::noDriverRuntimeException();
+    }
+
+    public function find($id)
```
Comment (kunicmarko20) [inline src/Model/NoDriverManager.php]: comment about type

File: src/Model/NoDriverManager.php [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+    {
+        SonataMediaBundle::noDriverRuntimeException();
+    }
+
+    public function create()
+    {
+        SonataMediaBundle::noDriverRuntimeException();
+    }
+
+    public function save($entity, $andFlush = true)
```
Comment (kunicmarko20) [inline src/Model/NoDriverManager.php]: comment about type

File: src/Model/NoDriverManager.php [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+    {
+        SonataMediaBundle::noDriverRuntimeException();
+    }
+
+    public function delete($entity, $andFlush = true)
```
Comment (kunicmarko20) [inline src/Model/NoDriverManager.php]: comment about type

File: src/Model/NoDriverManager.php [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+    {
+        SonataMediaBundle::noDriverRuntimeException();
+    }
+
+    public function getTableName()
```
Comment (kunicmarko20) [inline src/Model/NoDriverManager.php]: comment about type

File: src/DependencyInjection/SonataMediaExtension.php [hunk 8]
```diff
@@ -99,7 +99,7 @@ public function load(array $configs, ContainerBuilder $container)
         $loader->load('serializer.xml');
         $loader->load('command.xml');
 
-        if (!in_array(strtolower($config['db_driver']), ['doctrine_orm', 'doctrine_mongodb', 'doctrine_phpcr'])) {
+        if (!in_array(strtolower($config['db_driver']), ['doctrine_orm', 'doctrine_mongodb', 'doctrine_phpcr', 'no_driver'])) {
```
Comment (kunicmarko20) [inline src/DependencyInjection/SonataMediaExtension.php]: can we extract this array a `const` maybe, what do @sonata-project/contributors think?

File: src/Model/NoDriverManager.php [hunk 9]
```diff
@@ -0,0 +1,71 @@
...
+class NoDriverManager implements ManagerInterface
+{
+    public function getClass()
+    {
+        SonataMediaBundle::noDriverRuntimeException();
+    }
+
+    public function findAll()
+    {
+        SonataMediaBundle::noDriverRuntimeException();
```
Comment (jordisala1991) [inline src/Model/NoDriverManager.php]: Why don't we generate a new Exception class for this?

File: src/DependencyInjection/SonataMediaExtension.php (hunk 8 above)
Comment (jordisala1991) [reply src/DependencyInjection/SonataMediaExtension.php]: Sounds better, if we don't produce any BC breaks I would prefer that way too

File: src/Model/NoDriverManager.php (hunk 9 above)
Comment (covex-nn) [reply src/Model/NoDriverManager.php]: This error will be shown to developer in a browser, if a pack with additional configuration was not installed. Here is a screenshot how it is decorated by `symfony/debug` in dev environment:

Error message

That message could be updated! We could add instructions how to install a pack =)
But, i agree, that method should be removed. Can i use `Sonata\CoreBundle\Exception\InvalidParameterException`?

Comment (kunicmarko20) [reply src/Model/NoDriverManager.php]: I thought more about new exception class, `NoDriverException`?

Comment (covex-nn) [reply src/Model/NoDriverManager.php]: Added new `NoDriverException`

File: tests/Model/NoDriverManagerTest.php [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+class NoDriverManagerTest extends TestCase
+{
+    /**
+     * @dataProvider providerMethods
+     */
+    public function testException($method, array $arguments)
+    {
+        $this->expectException('Sonata\MediaBundle\Exception\NoDriverException');
+
+        $manager = new NoDriverManager();
```
Comment (kunicmarko20) [inline tests/Model/NoDriverManagerTest.php]: this var is not needed, can you just move `new NoDriverManager()` to method?

File: tests/Model/NoDriverManagerTest.php [hunk 11]
```diff
@@ -0,0 +1,45 @@
...
+use Sonata\MediaBundle\Model\NoDriverManager;
+
+class NoDriverManagerTest extends TestCase
+{
+    /**
+     * @dataProvider providerMethods
+     */
+    public function testException($method, array $arguments)
+    {
+        $this->expectException('Sonata\MediaBundle\Exception\NoDriverException');
```
Comment (kunicmarko20) [inline tests/Model/NoDriverManagerTest.php]: Can you use `NoDriverException::class`

File: tests/Generator/NoDriverGeneratorTest.php [hunk 12]
```diff
@@ -0,0 +1,28 @@
...
+
+use PHPUnit\Framework\TestCase;
+use Sonata\MediaBundle\Generator\NoDriverGenerator;
+use Sonata\MediaBundle\Model\MediaInterface;
+
+class NoDriverGeneratorTest extends TestCase
+{
+    public function testException()
+    {
+        $this->expectException('Sonata\MediaBundle\Exception\NoDriverException');
```
Comment (kunicmarko20) [inline tests/Generator/NoDriverGeneratorTest.php]: same here, use `::class`

File: tests/Model/NoDriverManagerTest.php (hunk 10 above)
Comment (covex-nn) [reply tests/Model/NoDriverManagerTest.php]: Fixed =)

File: src/DependencyInjection/SonataMediaExtension.php (hunk 8 above)
Comment (kunicmarko20) [reply src/DependencyInjection/SonataMediaExtension.php]: ah, forgot about this @covex-nn can you move this without doing a BC break?

Comment (covex-nn) [reply src/DependencyInjection/SonataMediaExtension.php]: Sure! i'll do it a little bit later (i must go right now)

Comment (kunicmarko20) [reply src/DependencyInjection/SonataMediaExtension.php]: Blocked merge, thank you for helping!

Comment (covex-nn) [reply src/DependencyInjection/SonataMediaExtension.php]: @kunicmarko20 all done, please review )

File: src/DependencyInjection/Configuration.php [hunk 13]
```diff
@@ -32,7 +37,13 @@ public function getConfigTreeBuilder()
 
         $node
             ->children()
-                ->scalarNode('db_driver')->isRequired()->end()
+                ->scalarNode('db_driver')
+                    ->defaultValue('no_driver')
+                    ->validate()
+                        ->ifNotInArray(self::DB_DRIVERS)
+                        ->thenInvalid('SonataMediaBundle - Invalid db driver %s.')
```
Comment (kunicmarko20) [inline src/DependencyInjection/Configuration.php]: will it throw the same exception?

Comment (covex-nn) [reply src/DependencyInjection/Configuration.php]: Before my changes there was `\InvalidArgumentException`, and now it will throw a same exception, see https://github.com/symfony/config/blob/master/Definition/Builder/ExprBuilder.php#L187, but before container compilation started

File: src/Exception/NoDriverException.php [hunk 14]
```diff
@@ -0,0 +1,25 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Sonata\MediaBundle\Exception;
+
+/**
+ * @author Andrey F. Mindubaev <covex.mobile@gmail.com>
+ */
+class NoDriverException extends \RuntimeException
```
Comment (core23) [inline src/Exception/NoDriverException.php]: final?

File: src/Generator/NoDriverGenerator.php [hunk 15]
```diff
@@ -0,0 +1,28 @@
...
+use Sonata\MediaBundle\Exception\NoDriverException;
+use Sonata\MediaBundle\Model\MediaInterface;
+
+/**
+ * @internal
+ *
+ * @author Andrey F. Mindubaev <covex.mobile@gmail.com>
+ */
+class NoDriverGenerator implements GeneratorInterface
```
Comment (core23) [inline src/Generator/NoDriverGenerator.php]: final?

File: src/Model/NoDriverManager.php [hunk 16]
```diff
@@ -0,0 +1,88 @@
...
+
+use Sonata\CoreBundle\Model\ManagerInterface;
+use Sonata\MediaBundle\Exception\NoDriverException;
+
+/**
+ * @internal
+ *
+ * @author Andrey F. Mindubaev <covex.mobile@gmail.com>
+ */
+class NoDriverManager implements ManagerInterface
```
Comment (core23) [inline src/Model/NoDriverManager.php]: final?

File: src/Exception/NoDriverException.php (hunk 14 above)
Comment (covex-nn) [reply src/Exception/NoDriverException.php]: Fixed

**Comment by covex-nn** [comment]
I pushed a commit with recipe for MediaBundle; after new version will be released i will create a PR

* See https://github.com/covex-nn/recipes-contrib/compare/master...sonata-media
* If there something i should add (like url to docs, or that tip about 'quality' that it should not be greater than 100 for png) - please tell me

**Comment by kunicmarko20** [comment]
I think we need to mention that uploads folder should be writable

File: src/DependencyInjection/Configuration.php [hunk 17]
```diff
@@ -32,7 +37,13 @@ public function getConfigTreeBuilder()
 
         $node
             ->children()
-                ->scalarNode('db_driver')->isRequired()->end()
+                ->scalarNode('db_driver')
+                    ->defaultValue('no_driver')
```
Comment (greg0ire) [inline src/DependencyInjection/Configuration.php]: Please add a call to `info()`

File: src/Exception/NoDriverException.php [hunk 18]
```diff
@@ -0,0 +1,25 @@
...
+namespace Sonata\MediaBundle\Exception;
+
+/**
+ * @author Andrey F. Mindubaev <covex.mobile@gmail.com>
+ */
+final class NoDriverException extends \RuntimeException
+{
+    const DEFAULT_MESSAGE = 'The child node "db_driver" at path "sonata_media" must be configured.';
+
+    public function __construct($message = self::DEFAULT_MESSAGE, $code = 0, \Throwable $previous = null)
```
Comment (greg0ire) [inline src/Exception/NoDriverException.php]: `\Throwable` is not available with php 5

File: src/Exception/NoDriverException.php [hunk 19]
```diff
@@ -0,0 +1,25 @@
...
+ */
+
+namespace Sonata\MediaBundle\Exception;
+
+/**
+ * @author Andrey F. Mindubaev <covex.mobile@gmail.com>
+ */
+final class NoDriverException extends \RuntimeException
+{
+    const DEFAULT_MESSAGE = 'The child node "db_driver" at path "sonata_media" must be configured.';
```
Comment (greg0ire) [inline src/Exception/NoDriverException.php]: Why put this in a constant? It's public now, and it's only ever used once.

File: src/Resources/config/no_driver.xml [hunk 20]
```diff
@@ -0,0 +1,8 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<container xmlns="http://symfony.com/schema/dic/services" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
+    <services>
+        <service id="sonata.media.manager.media" class="Sonata\MediaBundle\Model\NoDriverManager"/>
+        <service id="sonata.media.manager.gallery" class="Sonata\MediaBundle\Model\NoDriverManager"/>
+        <service id="sonata.media.generator.default" class="Sonata\MediaBundle\Generator\NoDriverGenerator"/>
```
Comment (greg0ire) [inline src/Resources/config/no_driver.xml]: Please mark service than can be private as such

File: src/Resources/config/no_driver_admin.xml [hunk 21]
```diff
@@ -0,0 +1,3 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<container xmlns="http://symfony.com/schema/dic/services" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
+</container>
```
Comment (greg0ire) [inline src/Resources/config/no_driver_admin.xml]: ?

Comment (covex-nn) [reply src/Resources/config/no_driver_admin.xml]: This file is loaded from [SonataMediaExtension.php](https://github.com/sonata-project/SonataMediaBundle/blob/3.x/src/DependencyInjection/SonataMediaExtension.php#L147) when SonataAdminBundle is enabled. So, i created an empty file for that case.

File: src/Resources/config/no_driver.xml (hunk 20 above)
Comment (covex-nn) [reply src/Resources/config/no_driver.xml]: @greg0ire only `sonata.media.generator.default` can be private, two others must be public. I will add `public="true"` there

File: src/DependencyInjection/Configuration.php (hunk 17 above)
Comment (covex-nn) [reply src/DependencyInjection/Configuration.php]: Added `->info('Choose persistence mechanism driver from the following list: "doctrine_orm", "doctrine_mongodb", "doctrine_phpcr"')`

File: src/Exception/NoDriverException.php (hunk 18 above)
Comment (covex-nn) [reply src/Exception/NoDriverException.php]: Fixed

File: src/Resources/config/no_driver_admin.xml (hunk 21 above)
Comment (greg0ire) [reply src/Resources/config/no_driver_admin.xml]: Please add an XML comment to explain this.

File: src/Exception/NoDriverException.php (hunk 19 above)
Comment (greg0ire) [reply src/Exception/NoDriverException.php]: Yeah but why not do this: https://3v4l.org/WmvS8 or this: https://3v4l.org/ROnrq?

File: src/Resources/config/no_driver_admin.xml [hunk 22]
```diff
@@ -1,3 +1,6 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <container xmlns="http://symfony.com/schema/dic/services" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
+    <!--
+     This file will be loaded when SonataAdminBundle is enabled and db_driver has it's default value, not corresponding to real persistence mechanism.
```
Comment (greg0ire) [inline src/Resources/config/no_driver_admin.xml]: - it's => its
- linebreak that line 4

 and we're good

File: src/Exception/NoDriverException.php (hunk 19 above)
Comment (covex-nn) [reply src/Exception/NoDriverException.php]: Just i did not think, that it is important. Next time i will try not to create new not necessary entities

File: src/Resources/config/no_driver_admin.xml (hunk 22 above)
Comment (covex-nn) [reply src/Resources/config/no_driver_admin.xml]: Fixed

**Comment by greg0ire** [comment]
Thanks @covex-nn !
