### PR TITLE
LiipImagineThumbnail thumbnail path resolve

### LINKED ISSUE #994: Liip Imagine Bundle 1.5.x
I was wondering if anyone has recently been successful to integrate the LiipImagineBundle with the media bundle? I tried all the means possible but it seems like I failed in something or the other every time. I think the documentation is also too old. Can anyone who has been successful in integrating the bundle please give some hints for successfully making the bundle work? Thanks in advance.

### PR DESCRIPTION
**Pull request by schauer**
I continue the PR from cengizhancaliskan https://github.com/sonata-project/SonataMediaBundle/pull/1242
"I am targeting this branch, because , The LiipImagine dependency being used is outdated and no longer maintained. Actually i fixed relative image path."

Closes #994

## Changelog

```markdown


### Fixed
- LiipImagine generatePublicUrl updated to work with latest version of that bundle
- Relative path when path it is already an url

```

### CODE REVIEW

File: src/Thumbnail/LiipImagineThumbnail.php [hunk 1]
```diff
@@ -14,19 +14,34 @@
...
 use Sonata\MediaBundle\Provider\MediaProviderInterface;
+use Symfony\Component\Routing\RouterInterface;
 
 class LiipImagineThumbnail implements ThumbnailInterface
 {
+    /**
+     * @deprecated Since version 3.3, will be removed in 4.0.
+     * @var RouterInterface
+     */
+    protected $router;
```
Comment (greg0ire) [inline src/Thumbnail/LiipImagineThumbnail.php]: Should be private

File: Tests/Security/LiipImagineThumbnailTest.php [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+
+namespace Sonata\MediaBundle\Tests\Security;
+
+use Gaufrette\Adapter\InMemory;
+use Gaufrette\File;
+use Gaufrette\Filesystem;
+use Sonata\MediaBundle\Tests\Helpers\PHPUnit_Framework_TestCase;
+use Sonata\MediaBundle\Thumbnail\LiipImagineThumbnail;
+
+class LiipImagineThumbnailTest extends PHPUnit_Framework_TestCase
```
Comment (greg0ire) [inline Tests/Security/LiipImagineThumbnailTest.php]: We no longer extend `Sonata\MediaBundle\Tests\Helpers\PHPUnit_Framework_TestCase` in tests, please have a look at the other test cases

File: Tests/Security/LiipImagineThumbnailTest.php [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+{
+    public function testGenerate()
+    {
+        $cacheManager = $this->createMock('Liip\ImagineBundle\Imagine\Cache\CacheMenager');
```
Comment (greg0ire) [inline Tests/Security/LiipImagineThumbnailTest.php]: `CacheMenager` does not exist (typo), and you should use the `::class` notation

Comment (greg0ire) [reply Tests/Security/LiipImagineThumbnailTest.php]: Also, consider using the real thing instead of a mock if that's easy.

**Comment by schauer** [comment]
@greg0ire Can you please review your changes requests? I hope everything is fine now.

File: .travis.yml [hunk 4]
```diff
@@ -72,6 +72,8 @@ matrix:
       env: SONATA_ADMIN='dev-master as 3.x-dev'
     - php: '7.2'
       env: SYMFONY_DEPRECATIONS_HELPER=0
+    - php: '7.2'
```
Comment (jordisala1991) [inline .travis.yml]: this should not get modified from here

File: .travis/before_install_test.sh [hunk 5]
```diff
@@ -23,3 +23,4 @@ if [ "$SYMFONY" != "" ]; then composer require "symfony/symfony:$SYMFONY" --no-u
 if [ "$DOCTRINE_ODM" != "" ]; then composer require "doctrine/mongodb-odm:$DOCTRINE_ODM" --no-update; fi;
 if [ "$SONATA_CORE" != "" ]; then composer require "sonata-project/core-bundle:$SONATA_CORE" --no-update; fi;
 if [ "$SONATA_ADMIN" != "" ]; then composer require "sonata-project/admin-bundle:$SONATA_ADMIN" --no-update; fi;
+if [ "$LIIP_IMAGINE_BUNDLE" != "" ]; then composer require "liip/imagine-bundle:$LIIP_IMAGINE_BUNDLE" --no-update; fi;
```
Comment (jordisala1991) [inline .travis/before_install_test.sh]: this file is handled by dev-kit too

File: composer.json [hunk 6]
```diff
@@ -78,7 +78,7 @@
         "symfony/phpunit-bridge": "^3.3 || ^4.0"
     },
     "suggest": {
-        "liip/imagine-bundle": "^0.9",
+        "liip/imagine-bundle": "If you want on-the-fly thumbnail generation or image filtering (scale, crop, watermark...)",
```
Comment (jordisala1991) [inline composer.json]: Shouldn't we add liip/imagine-bundle to require-dev and conflict section? Just to be sure people install the required version and we tests against it too.

File: src/Resources/config/provider.xml [hunk 7]
```diff
@@ -19,7 +19,7 @@
             <argument type="string">%sonata.media.thumbnail.format.default%</argument>
         </service>
         <service id="sonata.media.thumbnail.liip_imagine" class="%sonata.media.thumbnail.liip_imagine%">
-            <argument type="service" id="router"/>
+            <argument type="service" id="liip_imagine.cache.manager"/>
```
Comment (jordisala1991) [inline src/Resources/config/provider.xml]: this is loaded always? because someone could not have this service defined because it is not using liip imagine

File: .travis.yml (hunk 4 above)
Comment (greg0ire) [reply .travis.yml]: Should be removed just before merging

**Comment by schauer** [comment]
Hi @jordisala1991 can you please review your requests? Thanks.

File: src/Provider/ImageProvider.php [hunk 8]
```diff
@@ -179,6 +179,11 @@ public function generatePublicUrl(MediaInterface $media, $format)
             $path = $this->thumbnail->generatePublicUrl($this, $media, $format);
         }
 
+        // if path is url, do not action
```
Comment (greg0ire) [inline src/Provider/ImageProvider.php]: It's usually "do not" + verb, and "action" is a noun

File: composer.json [hunk 9]
```diff
@@ -56,6 +56,7 @@
     "conflict": {
         "friendsofsymfony/rest-bundle": "<1.7.4 || >=3.0",
         "jms/serializer": "<0.13",
+        "liip/imagine-bundle": "<1.0",
```
Comment (core23) [inline composer.json]: Is there a reason why we test version `^1.9`, but only conflict versions lower than 1.0? Shouln't they match when running tests?

File: src/Provider/ImageProvider.php (hunk 8 above)
Comment (schauer) [reply src/Provider/ImageProvider.php]: Not my words ☺, but I will review this comment.

File: composer.json (hunk 9 above)
Comment (schauer) [reply composer.json]: Hmm, correct. Should I remove this line entirely?

Comment (jordisala1991) [reply composer.json]: No, just do <1.9

Comment (schauer) [reply composer.json]: @core23  can you please review your requested changes?

File: src/Thumbnail/LiipImagineThumbnail.php [hunk 10]
```diff
@@ -11,40 +11,64 @@
...
 
 class LiipImagineThumbnail implements ThumbnailInterface
 {
     /**
+     * @deprecated Since version 3.3, will be removed in 4.0.
+     *
      * @var RouterInterface
      */
-    protected $router;
+    private $router;
```
Comment (greg0ire) [inline src/Thumbnail/LiipImagineThumbnail.php]: This is a BC-break

Comment (jordisala1991) [reply src/Thumbnail/LiipImagineThumbnail.php]: Keep the property protected please

Comment (schauer) [reply src/Thumbnail/LiipImagineThumbnail.php]: sonata-project_sonatamediabundle_pull_1393_pullrequestreview-97404967
sonata-project_sonatamediabundle_pull_1393_pullrequestreview-98846546

Hope this will PR will have an end :smile:.

Comment (greg0ire) [reply src/Thumbnail/LiipImagineThumbnail.php]: You're almost there!

File: tests/Thumbnail/LiipImagineThumbnailTest.php [hunk 11]
```diff
@@ -0,0 +1,118 @@
...
+        $media = new Media();
+        $media->setName('ASDASDAS.png');
+        $media->setProviderReference('ASDASDAS.png');
+        $media->setId(1023456);
+        $media->setContext('default');
+
+        $thumbnail->generate($provider, $media);
+        $this->assertSame('default/0011/24/ASDASDAS.png', $thumbnail->generatePublicUrl($provider, $media, MediaProviderInterface::FORMAT_ADMIN));
+        $this->assertSame('cache/media/default/0011/24/ASDASDAS.png', $thumbnail->generatePublicUrl($provider, $media, 'mycontext_medium'));
+    }
```
Comment (greg0ire) [inline tests/Thumbnail/LiipImagineThumbnailTest.php]: Please add a test for the deprecated path

```php
<?php
/**
 * @group legacy
 * @expectedDeprecationMessage part of the expected message
 */
public function testWhateverYouWantToCallIt()
{
   // instantiate the object in the deprecated way and check it still works
}
```

Comment (schauer) [reply tests/Thumbnail/LiipImagineThumbnailTest.php]: Sorry, I'm afraid I'm not capable of that. At this point I would like to hand over to someone else. Thanks all for your help!

Comment (greg0ire) [reply tests/Thumbnail/LiipImagineThumbnailTest.php]: I'll try to do it this week-end then, can you please reopen?

Comment (greg0ire) [reply tests/Thumbnail/LiipImagineThumbnailTest.php]: And can you please click the "allow maintainers to push" checkbox? Should be bottom right

Comment (greg0ire) [reply tests/Thumbnail/LiipImagineThumbnailTest.php]: Ah wait nevermind, I can reopen.

File: tests/Thumbnail/LiipImagineThumbnailTest.php [hunk 12]
```diff
@@ -0,0 +1,118 @@
...
+
+        $provider = $this->createMock('Sonata\MediaBundle\Provider\MediaProviderInterface');
+        $provider->expects($this->any())->method('requireThumbnails')->will($this->returnValue(true));
+        $provider->expects($this->any())->method('getReferenceFile')->will($this->returnValue($referenceFile));
+        $provider->expects($this->any())->method('getFormats')->will($this->returnValue($formats));
+        $provider->expects($this->any())->method('getResizer')->will($this->returnValue($resizer));
+        $provider->expects($this->any())->method('generatePrivateUrl')->will($this->returnValue('/my/private/path'));
+        $provider->expects($this->any())->method('generatePublicUrl')->will($this->returnValue('/my/public/path'));
+        $provider->expects($this->any())->method('getFilesystem')->will($this->returnValue($filesystem));
+        $provider = $this->getProvider();
```
Comment (greg0ire) [inline tests/Thumbnail/LiipImagineThumbnailTest.php]: All theses assertions, only to replace the provider in the end?

**Comment by jordisala1991** [comment]
Can you rebase @greg0ire ?

**Comment by greg0ire** [comment]
Sure thing

File: src/Thumbnail/LiipImagineThumbnail.php (hunk 10 above)
Comment (greg0ire) [reply src/Thumbnail/LiipImagineThumbnail.php]: Oh ok I didn't realise what this was, the first diff made me think that this was a new property, because it was all green, but it isn't, which means we should revert this change

Comment (greg0ire) [reply src/Thumbnail/LiipImagineThumbnail.php]: Ah that's because you removed it at first, and then added it back, I understand what happened now.

Comment (greg0ire) [reply src/Thumbnail/LiipImagineThumbnail.php]: `protected` restored

File: tests/Provider/ImageProviderTest.php [hunk 13]
```diff
@@ -48,7 +48,6 @@ public function getProvider($allowedExtensions = [], $allowedMimeTypes = [], $bo
         $filesystem->expects($this->any())->method('get')->will($this->returnValue($file));
 
         $cdn = new Server('/uploads/media');
-
```
Comment (greg0ire) [inline tests/Provider/ImageProviderTest.php]: Dunno why you changed this, I'll remove that change.

**Comment by jordisala1991** [comment]
Lets do this, thank you @schauer @greg0ire and everyone who contributed to this PR

**Comment by greg0ire** [comment]
Thanks, was a cool experience to use git in a truly decentralized way
